name: HockeyMOM
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - alsa-lib=1.2.9=hd590300_0
  - aom=3.5.0=h27087fc_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attr=2.5.1=h166bdaf_1
  - av=10.0.0=py38h2d6b4c4_3
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2023.7.22=pyhd8ed1ab_0
  - clang=10.0.1=default_hb85057a_2
  - clang-12=12.0.1=default_ha53f305_4
  - cmake=3.26.4=hcfe8598_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - epoxy=1.5.10=h166bdaf_1
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=6.0.0=gpl_hdbbbd96_103
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_13
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_1
  - glib=2.76.4=hfc55251_0
  - glib-tools=2.76.4=hfc55251_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-libav=1.22.5=hd5f137f_0
  - gst-plugins-base=1.22.5=hf7dbed1_0
  - gstreamer=1.22.5=h98fc4e7_0
  - gtk3=3.24.38=hf583ffa_0
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_13
  - harfbuzz=7.3.0=hdb3a94d_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=72.1=hcb278e6_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.1=h659d440_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=3.0=h295c915_0
  - libass=0.17.1=hc9aadba_0
  - libcap=2.67=he9d0100_0
  - libclang-cpp10=10.0.1=default_hb85057a_2
  - libclang-cpp12=12.0.1=default_ha53f305_4
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.1.2=hca28451_1
  - libdc1394=2.2.7=h59595ed_0
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm12=12.0.1=hf817b99_2
  - libllvm14=14.0.6=hcd5def8_3
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6a678d5_1
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h27cfd23_0
  - libusb=1.0.26=h0b4f0b6_100
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libva=2.19.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.0=hcb278e6_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=h166bdaf_4
  - llvmlite=0.40.1=py38h94a1851_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.8.1=hc379101_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numba=0.57.1=py38hd559b08_0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - openblas=0.3.23=pthreads_h855a84d_0
  - openh264=2.3.1=hcb278e6_2
  - openssl=3.1.1=hd590300_1
  - p11-kit=0.24.1=hc5aa10d_0
  - pango=1.50.14=heaa33ce_1
  - pcre2=10.40=hc3806b6_0
  - pillow=9.3.0=py38h6a678d5_2
  - pip=22.3.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.8.12=h0744224_3_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.7.0=py3.8_cuda10.2.89_cudnn7.6.5_0
  - readline=8.2=h5eee18b_0
  - rhash=1.4.3=h166bdaf_0
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - svt-av1=1.6.0=h59595ed_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.8.0=py38_cu102
  - typing_extensions=4.4.0=py38h06a4308_0
  - wayland=1.22.0=h8c25dac_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.39=hd590300_0
  - xorg-compositeproto=0.4.2=h7f98852_1001
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.4.0
      - asttokens==2.2.1
      - astunparse==1.6.3
      - backcall==0.2.0
      - cachetools==5.3.1
      - cameratransform==1.2
      - charset-normalizer==3.1.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.33
      - cython-bbox==0.1.3
      - decorator==5.1.1
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - flatbuffers==23.5.26
      - fonttools==4.38.0
      - fvcore==0.1.5.post20221221
      - gast==0.4.0
      - google-auth==2.20.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5py==3.8.0
      - idna==3.4
      - iopath==0.1.10
      - ipython==8.10.0
      - jax==0.4.12
      - jedi==0.18.2
      - joblib==1.2.0
      - keras==2.12.0
      - kiwisolver==1.4.4
      - kmeans-pytorch==0.3
      - lap==0.4.0
      - libclang==16.0.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - ml-dtypes==0.2.0
      - motmetrics==1.4.0
      - oauthlib==3.2.2
      - opencv-contrib-python==4.7.0.68
      - opencv-python==4.7.0.68
      - openpyxl==3.1.0
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - portalocker==2.7.0
      - progress==1.6
      - prompt-toolkit==3.0.36
      - protobuf==4.23.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0
      - pygments==2.14.0
      - pynvml==11.4.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-version==0.0.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - seaborn==0.12.2
      - stack-data==0.6.2
      - tabulate==0.9.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.5.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tqdm==4.64.1
      - traitlets==5.9.0
      - urllib3==1.26.16
      - wcwidth==0.2.6
      - werkzeug==2.3.6
      - wrapt==1.14.1
      - xmltodict==0.13.0
      - yacs==0.1.8
prefix: /home/colivier/.conda/envs/HockeyMOM
