model:
  backbone:
    type: dla34
    pretrained: True
    #pretrained_path: 'pretrained/centertrack/dla34/my_crowdhuman/model_140.pth'
    #pretrained_path: 'pretrained/dla34/centertrack_my_coco_ch_e90.pth'
    #pretrained_path: 'pretrained/dla34/centertrack_my_coco_ch_large.pth'
    #pretrained_path: '/mnt/ripper-data/pretrained/dla34/centertrack_my_coco_ch_e120_large.pth'
    pretrained_path: '/mnt/ripper-data/pretrained/dla34/centertrack_my_coco_ch_e120_large_last.pth'
    #pretrained_path: 'pretrained/dla34/my_coco_ch_e60.pth'
    #pretrained_path: 'pretrained/centertrack/crowdhuman.pth'
    #pretrained_path: 'pretrained/centertrack/coco_pose_tracking.pth'
    #pretrained_path: 'pretrained/centertrack/mot17_fulltrain.pth'
    # TODO: what is default for centertrack?
    # det_thres: 0.3

    train:

    test:

  tracker:
    type: centertrack
    pre_hm: true
    pre_thresh: 0.45
    track_thresh: 0.49


