application:
  name: deepstream-test2
---
dependencies:
- extension: NvDsSourceExt
  uuid: a632d022-3425-4848-9074-e6483ef74366
  version: 1.6.0
- extension: NvDsBaseExt
  uuid: 56d7e3ec-62c6-4652-bcc8-4f1c3b00df03
  version: 1.6.0
- extension: NvDsMuxDemuxExt
  uuid: 89b8398c-5820-4051-835c-a91f2d49766b
  version: 1.6.0
- extension: NvDsInferenceExt
  uuid: 0b02963e-c24e-4c13-ace0-c4cdf36c7c71
  version: 1.6.0
- extension: NvDsSampleModelsExt
  uuid: 909dc1ea-c654-44c1-97a3-0b8fec12141a
  version: 1.7.0
- extension: NvDsTrackerExt
  uuid: f5aaeb53-e9b8-4317-87d1-9549d67c1638
  version: 1.6.0
- extension: NvDsVisualizationExt
  uuid: 25903cd4-fc5c-4139-987b-47bb27e8b424
  version: 1.6.0
- extension: NvDsOutputSinkExt
  uuid: 3fc9ad87-03e7-47a8-bbfc-8501c3f7ff2f
  version: 1.6.0
- extension: NvDsInferenceUtilsExt
  uuid: 27856a43-5ad4-4d8e-be36-0ec2cf9bbb58
  version: 1.6.0
---
components:
- name: single_source_input
  parameters:
    audio-out-%u: audio_output
    uri: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
    video-out-%u: video_output
  type: nvidia::deepstream::NvDsSingleSrcInput
- name: audio_output
  type: nvidia::deepstream::NvDsDynamicOutput
- name: video_output
  type: nvidia::deepstream::NvDsDynamicOutput
name: single_source_input
ui_property:
  position:
    x: -85.48816680908203
    y: -12.25196647644043
  state: 0
---
components:
- name: streammux
  parameters:
    batch-size: 1
    height: 1080
    video-in-%u: video_input
    video-out: video_output
    width: 1920
  type: nvidia::deepstream::NvDsStreamMux
- name: video_input
  type: nvidia::deepstream::NvDsOnRequestInput
- name: video_output
  type: nvidia::deepstream::NvDsStaticOutput
name: streammux
ui_property:
  position:
    x: 145.56698608398438
    y: 42.417335510253906
  state: 0
---
components:
- name: nv_ds_connection10..b470
  parameters:
    source: single_source_input/video_output
    target: streammux/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..b550
---
components:
- name: object_detector
  parameters:
    infer-model-config: resnet18_4_class_detector45..e550
    video-in: video_input
    video-out: video_output
  type: nvidia::deepstream::NvDsInferVideo
- name: video_input
  type: nvidia::deepstream::NvDsStaticInput
- name: video_output
  type: nvidia::deepstream::NvDsStaticOutput
- name: resnet18_4_class_detector45..e550
  type: nvidia::deepstream::NvDsResnet18_4ClassDetectorModel
name: object_detector
ui_property:
  position:
    x: 382.8111267089844
    y: 18.692914962768555
  state: 0
---
components:
- name: nv_ds_connection14..ba20
  parameters:
    source: streammux/video_output
    target: object_detector/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..5f98
---
components:
- name: tracker
  parameters:
    ll-config-file: /opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
    ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
    tracker-height: 384
    tracker-width: 640
    video-in: video_input
    video-out: video_output
  type: nvidia::deepstream::NvDsTracker
- name: video_input
  type: nvidia::deepstream::NvDsStaticInput
- name: video_output
  type: nvidia::deepstream::NvDsStaticOutput
name: tracker
ui_property:
  position:
    x: 605.6143188476562
    y: 54.79527282714844
  state: 0
---
components:
- name: nv_ds_connection18..6dd8
  parameters:
    source: object_detector/video_output
    target: tracker/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..ca20
---
components:
- name: vehicle_make_classifier
  parameters:
    infer-model-config: secondary_vehicle_make_classifier42..9cf8
    unique-id: 2
    video-in: video_input
    video-out: video_output
  type: nvidia::deepstream::NvDsInferVideo
- name: video_input
  type: nvidia::deepstream::NvDsStaticInput
- name: video_output
  type: nvidia::deepstream::NvDsStaticOutput
- name: secondary_vehicle_make_classifier42..9cf8
  type: nvidia::deepstream::NvDsSecondaryVehicleMakeClassifierModel
name: vehicle_make_classifier
ui_property:
  position:
    x: 831.5119018554688
    y: 37.25985336303711
  state: 0
---
components:
- name: nv_ds_connection22..8470
  parameters:
    source: tracker/video_output
    target: vehicle_make_classifier/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..bac8
---
components:
- name: nv_ds_connection26..c320
  parameters:
    source: vehicle_make_classifier/video_output
    target: vehicle_type_classifier/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..a710
---
components:
- name: vehicle_type_classifier
  parameters:
    infer-model-config: secondary_vehicle_type_classifier44..9a90
    unique-id: 4
    video-in: video_input
    video-out: video_output
  type: nvidia::deepstream::NvDsInferVideo
- name: video_input
  type: nvidia::deepstream::NvDsStaticInput
- name: video_output
  type: nvidia::deepstream::NvDsStaticOutput
- name: secondary_vehicle_type_classifier44..9a90
  type: nvidia::deepstream::NvDsSecondaryVehicleTypeClassifierModel
name: vehicle_type_classifier
ui_property:
  position:
    x: -264.1952209472656
    y: 402.99224853515625
  state: 0
---
components:
- name: onscreen_display
  parameters:
    video-in: video_input
    video-out: video_output
  type: nvidia::deepstream::NvDsOSD
- name: video_input
  type: nvidia::deepstream::NvDsStaticInput
- name: video_output
  type: nvidia::deepstream::NvDsStaticOutput
name: onscreen_display
ui_property:
  position:
    x: 254.16209411621094
    y: 480.47467041015625
  state: 0
---
components:
- name: nv_ds_connection34..0080
  parameters:
    source: vehicle_type_classifier/video_output
    target: onscreen_display/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..ea58
---
components:
- name: video_renderer
  parameters:
    video-in: video_input
  type: nvidia::deepstream::NvDsVideoRenderer
- name: video_input
  type: nvidia::deepstream::NvDsStaticInput
name: video_renderer
ui_property:
  position:
    x: 622.861328125
    y: 422.6490783691406
  state: 0
---
components:
- name: nv_ds_connection37..1ef0
  parameters:
    source: onscreen_display/video_output
    target: video_renderer/video_input
  type: nvidia::deepstream::NvDsConnection
name: node..4ba8
---
components:
- name: scheduler
  type: nvidia::deepstream::NvDsScheduler
name: scheduler
ui_property:
  position:
    x: 953.4622192382812
    y: 362.1917724609375
  state: 0
---
components:
- name: per_class_object_counting
  parameters:
    probe-connector: probe_connector
  type: nvidia::deepstream::NvDsPerClassObjectCounting
- name: probe_connector
  type: nvidia::deepstream::NvDsProbeConnector
name: per_class_object_counting
ui_property:
  position:
    x: 344.5144958496094
    y: 705.103759765625
  state: 0
---
components:
- name: nv_ds_probe41..1048
  parameters:
    io: vehicle_type_classifier/video_output
    probe-connector: per_class_object_counting/probe_connector
  type: nvidia::deepstream::NvDsProbe
name: node..3e80
