application:
  name: MyGraph
---
dependencies:
- extension: NvDsMuxDemuxExt
  uuid: 89b8398c-5820-4051-835c-a91f2d49766b
  version: 1.6.0
- extension: NvDsBaseExt
  uuid: 56d7e3ec-62c6-4652-bcc8-4f1c3b00df03
  version: 1.6.0
- extension: NvDsInferenceExt
  uuid: 0b02963e-c24e-4c13-ace0-c4cdf36c7c71
  version: 1.6.0
- extension: NvDsSampleModelsExt
  uuid: 909dc1ea-c654-44c1-97a3-0b8fec12141a
  version: 1.7.0
- extension: NvDsVisualizationExt
  uuid: 25903cd4-fc5c-4139-987b-47bb27e8b424
  version: 1.6.0
- extension: NvDsOutputSinkExt
  uuid: 3fc9ad87-03e7-47a8-bbfc-8501c3f7ff2f
  version: 1.6.0
- extension: NvDsInferenceUtilsExt
  uuid: 27856a43-5ad4-4d8e-be36-0ec2cf9bbb58
  version: 1.6.0
- extension: NvDsSourceExt
  uuid: a632d022-3425-4848-9074-e6483ef74366
  version: 1.6.0
- extension: NvDsSampleExt
  uuid: 44a711e4-8519-4a68-81e8-be7ee4af3ff0
  version: 1.6.0
---
components:
- name: Stream Muxer3
  parameters:
    batch-size: 1
    height: 1080
    video-in-%u: On Request Data Input4
    video-out: Static Data Output5
    width: 1920
  type: nvidia::deepstream::NvDsStreamMux
- name: On Request Data Input4
  type: nvidia::deepstream::NvDsOnRequestInput
- name: Static Data Output5
  type: nvidia::deepstream::NvDsStaticOutput
name: Stream Muxer
ui_property:
  position:
    x: 544.5
    y: 630.5
---
components:
- name: Video Inference6
  parameters:
    infer-model-config: 4-class Detector12
    video-in: Static Data Input8
    video-out: Static Data Output7
  type: nvidia::deepstream::NvDsInferVideo
- name: Static Data Output7
  type: nvidia::deepstream::NvDsStaticOutput
- name: Static Data Input8
  type: nvidia::deepstream::NvDsStaticInput
- name: 4-class Detector12
  type: nvidia::deepstream::NvDsResnet18_4ClassDetectorModel
name: Video Inference
ui_property:
  position:
    x: 860.0
    y: 906.5
---
components:
- name: On Screen Display9
  parameters:
    video-in: Static Data Input11
    video-out: Static Data Output10
  type: nvidia::deepstream::NvDsOSD
- name: Static Data Output10
  type: nvidia::deepstream::NvDsStaticOutput
- name: Static Data Input11
  type: nvidia::deepstream::NvDsStaticInput
name: On Screen Display
ui_property:
  position:
    x: 1327.0
    y: 896.0
---
components:
- name: NVidia Video Renderer13
  parameters:
    video-in: Static Data Input14
  type: nvidia::deepstream::NvDsVideoRenderer
- name: Static Data Input14
  type: nvidia::deepstream::NvDsStaticInput
name: NVidia Video Renderer
ui_property:
  position:
    x: 1646.5
    y: 1155.5
---
components:
- name: Deepstream Data Connection16
  parameters:
    source: Stream Muxer/Static Data Output5
    target: Video Inference/Static Data Input8
  type: nvidia::deepstream::NvDsConnection
name: node1
---
components:
- name: Deepstream Data Connection17
  parameters:
    source: Video Inference/Static Data Output7
    target: On Screen Display/Static Data Input11
  type: nvidia::deepstream::NvDsConnection
name: node2
---
components:
- name: Deepstream Data Connection18
  parameters:
    source: On Screen Display/Static Data Output10
    target: NVidia Video Renderer/Static Data Input14
  type: nvidia::deepstream::NvDsConnection
name: node3
---
components:
- name: Deepstream Scheduler19
  type: nvidia::deepstream::NvDsScheduler
name: Deepstream Scheduler
ui_property:
  position:
    x: 560.0
    y: 1189.5
  state: 0
---
components:
- name: Object Counter20
  parameters:
    probe-connector: Probe Connector21
  type: nvidia::deepstream::NvDsPerClassObjectCounting
- name: Probe Connector21
  type: nvidia::deepstream::NvDsProbeConnector
name: Object Counter
ui_property:
  position:
    x: 1268.0
    y: 1313.5
---
components:
- name: Probe Monitor22
  parameters:
    io: Video Inference/Static Data Output7
    probe-connector: Object Counter/Probe Connector21
  type: nvidia::deepstream::NvDsProbe
name: node4
---
components:
- name: Multi Source Input28
  parameters:
    audio-%u-out: Multiple Data Output30
    source-manip-action: Source Manipulation Action35
    video-%u-out: Multiple Data Output29
  type: nvidia::deepstream::NvDsMultiSrcInput
- name: Multiple Data Output29
  type: nvidia::deepstream::NvDsMultiOutput
- name: Multiple Data Output30
  type: nvidia::deepstream::NvDsMultiOutput
- name: Source Manipulation Action35
  type: nvidia::deepstream::NvDsSourceManipulationAction
name: Multi Source Input
ui_property:
  position:
    x: 129.0
    y: 593.5
  state: 0
---
components:
- name: Multi Data Connection31
  parameters:
    source: Multi Source Input/Multiple Data Output29
    target: Stream Muxer/On Request Data Input4
  type: nvidia::deepstream::NvDsMultiSrcConnection
name: node7
---
components:
- name: Source Add/Remove34
  parameters:
    max-num-sources: 4
    source-manip-action: Multi Source Input/Source Manipulation Action35
    uri: file:///opt/nvidia/deepstream/deepstream-7.1/samples/streams/sample_1080p_h265.mp4
  type: nvidia::deepstream::NvDsSampleSourceManipulator
name: Source Add/Remove
ui_property:
  position:
    x: 152.5
    y: 1131.5
