version: '3'
services:
  ssh_service:
    image: deepstream
    ports:
      - "${PORT_ON_HOST:-22299}:22299"
    volumes:
      - ${HOME}:${HOME}
      - ${HOME}/.ssh:${HOME}/.ssh
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/gshadow:/etc/gshadow:ro
      # - /etc/sudoers:/etc/sudoers:ro
    restart: always
