rink:
  name: "orlando_ice_den"
  location:
    city: "Orlando"
    state: "FL"
    country: "USA"
  dimensions:
    length: 180 feet
    width: 70 feet
    corner_radius: 20 feet
  surface_type: "Ice"
  seating_capacity: 100
  teams:
    home_team:
      name: "Cougars"
      colors: ["Blue", "Gray"]
  facilities:
    locker_rooms: 4
    concession_stands: 0
    restrooms: 3
  parking:
    capacity: 100
    price: 0 dollars
  tracking:
    cam_ignore_largest: false
  camera:
    fixed_edge_scaling_factor: 0.8
