rink:
  name: "roseville2"
  location:
    city: "Roseville"
    state: "CA"
    country: "USA"
  dimensions:
    length: 200 feet
    width: 85 feet
    corner_radius: 28 feet
  surface_type: "Ice"
  seating_capacity: 400
  teams:
    home_team:
      name: "Capital Thunder"
      colors: ["Purple", "Gray", "Black"]
  facilities:
    locker_rooms: 4
    concession_stands: 0
    restrooms: 4
  parking:
    capacity: 200
    price: 0 dollars  
  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 25.0
