rink:
  name: "vallco"
  location:
    city: "San Jose"
    state: "CA"
    country: "USA"
  dimensions:
    length: 200 feet
    width: 85 feet
    corner_radius: 28 feet
  surface_type: "Ice"
  seating_capacity: 100
  teams:
    home_team:
      name: "Jr Sharks"
      colors: ["Teal"]
  facilities:
    locker_rooms: 20
    concession_stands: 2
    restrooms: 10
  parking:
    capacity: 1000
    price: 0 dollars
  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: [25.0, 75.0]
