# version: '3.8'

services:
  hmbase:
    image: hmbase
    ports:
      - "${PORT_ON_HOST:-22298}:22298"
    volumes:
      - ${HOME}:${HOME}
      - ${HOME}/.ssh:${HOME}/.ssh
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/gshadow:/etc/gshadow:ro
      - /etc/sudoers:/etc/sudoers:ro
    restart: always
