name: ubuntu-gpu
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-aarch64_curr_repodata_hack=4=h57d6b7b_13
  - adwaita-icon-theme=43=unix_0
  - alsa-lib=1.2.10=hd590300_0
  - aom=3.7.1=h59595ed_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attr=2.5.1=h166bdaf_1
  - boost-cpp=1.82.0=h44aadfe_6
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.22.1=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - ccache=4.8.1=h1fcd64f_0
  - cmake=3.26.4=hcfe8598_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - elfutils=0.189=h6f2b95c_1
  - epoxy=1.5.10=h166bdaf_1
  - exiv2=0.27.6=hb9a316c_1
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=6.1.0=gpl_h402741f_101
  - fftw=3.3.10=nompi_hc118613_108
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.10=h829c605_4
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glcontext=2.5.0=py38h17151c0_0
  - glew=2.1.0=h9c3ff4c_2
  - glfw=3.3.8=hd590300_2
  - glib=2.78.1=hfc55251_1
  - glib-networking=2.78.0=h8eaaec1_0
  - glib-tools=2.78.1=hfc55251_1
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h59595ed_0
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=8.1.0=h28d9a01_0
  - gst-plugins-bad=1.22.6=h06bf7ac_0
  - gst-plugins-base=1.22.7=h8e1006c_0
  - gst-plugins-good=1.22.7=h16e77d8_0
  - gstreamer=1.22.7=h98fc4e7_0
  - gtk2=2.24.33=h90689f9_2
  - gtk3=3.24.38=h280cfa0_1
  - gts=0.7.6=h977cf35_4
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf5=1.14.2=nompi_h4f84152_100
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=73.2=h59595ed_0
  - imath=3.1.9=hfc55251_0
  - jack=1.9.22=h7c63dc7_2
  - kernel-headers_linux-aarch64=4.18.0=h5b4a56d_13
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lapack=3.9.0=netlib
  - lcms2=2.15=hb7c19ff_3
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lemon=1.3.1=hc5b7c51_7
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.2=h59595ed_1
  - libarchive=3.7.2=h039dbb9_0
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=20_linux64_openblas
  - libboost=1.82.0=h6fcfa73_6
  - libboost-devel=1.82.0=h00ab1b0_6
  - libboost-headers=1.82.0=ha770c72_6
  - libboost-python=1.82.0=py38hae673b5_6
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=20_linux64_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.4.0=hca28451_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.19=hd590300_0
  - libdrm=2.4.114=h166bdaf_0
  - libdrm-cos7-aarch64=2.4.97=h9b0a68f_1105
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgcrypt=1.10.2=hd590300_0
  - libgd=2.3.3=h119a65a_9
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.1=h783c2da_1
  - libglu=9.0.0=hac7e632_1003
  - libglvnd-cos7-aarch64=1.0.1=h9b0a68f_1105
  - libglvnd-glx-cos7-aarch64=1.0.1=h9b0a68f_1105
  - libgomp=13.2.0=h807b86a_3
  - libgpg-error=1.47=h71f35ed_0
  - libhiredis=1.0.2=h2cc385e_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - liblapacke=3.9.0=20_linux64_openblas
  - libllvm17=17.0.5=h5cf9203_0
  - libmicrohttpd=0.9.77=h97afed2_0
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpano13=2.9.20rc2=pl5321hfc037ee_7
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libpsl=0.21.2=h3253dac_1
  - librsvg=2.56.3=h98fae49_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsoup=3.4.4=hb337396_0
  - libsqlite=3.44.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libsystemd0=254=h3516f8a_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libtool=2.4.7=h27087fc_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libva=2.20.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.3.2=h658648e_1
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.6.0=h5d7e998_0
  - libxml2=2.11.6=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mesa-khr-devel-cos7-aarch64=18.3.4=h9b0a68f_1105
  - mesa-libegl-cos7-aarch64=18.3.4=h9b0a68f_1105
  - mesa-libegl-devel-cos7-aarch64=18.3.4=h9b0a68f_1105
  - mesa-libgbm-cos7-aarch64=18.3.4=h9b0a68f_1105
  - mesa-libgl-cos7-aarch64=18.3.4=h9b0a68f_1105
  - mesa-libglapi-cos7-aarch64=18.3.4=h9b0a68f_1105
  - mesalib=23.2.1=h6b56f8e_0
  - mpg123=1.32.3=h59595ed_0
  - ncurses=6.4=h59595ed_2
  - nettle=3.8.1=hc379101_1
  - numpy=1.24.4=py38h59b608b_0
  - openexr=3.2.1=h3f0fd8d_0
  - openh264=2.3.1=hcb278e6_2
  - openssl=3.2.0=hd590300_1
  - p11-kit=0.24.1=hc5aa10d_0
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.42=hcad00b1_0
  - perl=5.32.1=4_hd590300_perl5
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=hb77b528_5
  - pybind11=2.11.1=py38h7f3f72f_2
  - pybind11-global=2.11.1=py38h7f3f72f_2
  - python=3.8.18=hd12c33a_0_cpython
  - python_abi=3.8=4_cp38
  - readline=8.2=h8228510_1
  - rhash=1.4.3=hd590300_2
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sqlite=3.44.0=h2c6b66d_0
  - svt-av1=1.7.0=h59595ed_0
  - sysroot_linux-aarch64=2.17=h5b4a56d_13
  - tk=8.6.13=noxft_h4845f30_101
  - vigra=1.11.2=py38h9f585f3_3
  - wayland=1.22.0=h8c25dac_1
  - wheel=0.41.3=pyhd8ed1ab_0
  - wxwidgets=3.2.4=h3856fee_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.40=hd590300_0
  - xorg-compositeproto=0.4.2=h7f98852_1001
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-glproto=1.4.17=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml-cpp=0.8.0=h59595ed_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - mpmath==1.3.0
      - pyyaml==6.0.1
      - sympy==1.12
      - typing-extensions==4.8.0
prefix: /home/colivier/.conda/envs/ubuntu-gpu
