game:
  boundaries:
    upper:
    - - 191
      - 1068
      - 307
      - 1068
    - - 301
      - 1066
      - 472
      - 996
    - - 472
      - 996
      - 847
      - 907
    - - 841
      - 907
      - 1245
      - 827
    - - 1241
      - 827
      - 1610
      - 797
    - - 1604
      - 795
      - 2131
      - 786
    - - 2126
      - 787
      - 2692
      - 804
    - - 2690
      - 804
      - 3299
      - 848
    - - 3290
      - 849
      - 3813
      - 916
    - - 3813
      - 916
      - 4094
      - 964
    - - 4094
      - 964
      - 4394
      - 1029
    - - 4391
      - 1029
      - 4860
      - 1156
    - - 4860
      - 1156
      - 5050
      - 1250
    lower:
    - - 125
      - 1038
      - 298
      - 1033
    - - 292
      - 1077
      - 803
      - 1463
    - - 797
      - 1458
      - 2096
      - 1984
    - - 2085
      - 1984
      - 3913
      - 1878
    - - 3903
      - 1877
      - 4695
      - 1497
    - - 4680
      - 1502
      - 5052
      - 1245
    - - 5056
      - 1142
      - 5369
      - 1135
rink:
  scoreboard:
    perspective_polygon:
    - - 657
      - 736
    - - 899
      - 695
    - - 909
      - 754
    - - 671
      - 797
