game:
  name: "blackhawks-1"
  rink: "vallco"
  boundaries:
    upper:
    - - 41
      - 962
      - 307
      - 898
    - - 307
      - 898
      - 628
      - 747
    - - 628
      - 747
      - 974
      - 611
    - - 973
      - 611
      - 1310
      - 519
    - - 1310
      - 519
      - 1702
      - 467
    - - 1702
      - 467
      - 2013
      - 468
    - - 2013
      - 468
      - 2264
      - 439
    - - 2263
      - 440
      - 2605
      - 444
    - - 2605
      - 444
      - 2867
      - 480
    - - 2867
      - 480
      - 3116
      - 544
    - - 3116
      - 544
      - 3272
      - 592
    - - 3272
      - 592
      - 3468
      - 671
    - - 3469
      - 672
      - 3722
      - 784
    - - 3722
      - 784
      - 3975
      - 789
    lower:
    - - 35
      - 908
      - 309
      - 885
    - - 309
      - 885
      - 600
      - 1437
    - - 600
      - 1437
      - 771
      - 1627
    - - 3318
      - 1581
      - 3789
      - 808
    - - 3780
      - 737
      - 4016
      - 730
rink:
  scoreboard:
    perspective_polygon:
    - - 3663
      - 605
    - - 3740
      - 641
    - - 3716
      - 711
    - - 3641
      - 674
