game:
  boundaries:
    upper:
    - - 145
      - 1143
      - 305
      - 1130
    - - 305
      - 1130
      - 478
      - 1058
    - - 479
      - 1056
      - 905
      - 935
    - - 905
      - 935
      - 1268
      - 854
    - - 1259
      - 851
      - 1645
      - 802
    - - 1640
      - 802
      - 2087
      - 781
    - - 2083
      - 782
      - 2680
      - 778
    - - 2679
      - 778
      - 3221
      - 797
    - - 3219
      - 798
      - 3716
      - 835
    - - 3710
      - 836
      - 4135
      - 879
    - - 4124
      - 879
      - 4429
      - 942
    - - 4426
      - 942
      - 4796
      - 1037
    - - 4796
      - 1037
      - 5055
      - 1133
    - - 2341
      - 833
      - 2374
      - 835
    - - 2770
      - 841
      - 2801
      - 838
    - - 2881
      - 833
      - 2925
      - 829
    - - 3212
      - 850
      - 3250
      - 849
    - - 2400
      - 816
      - 2422
      - 814
    - - 2491
      - 819
      - 2521
      - 821
    lower:
    - - 89
      - 1088
      - 289
      - 1060
    - - 289
      - 1135
      - 937
      - 1575
    - - 927
      - 1571
      - 2307
      - 2013
    - - 3771
      - 1833
      - 4654
      - 1425
    - - 4650
      - 1424
      - 5055
      - 1133
    - - 5055
      - 910
      - 5429
      - 901
rink:
  scoreboard:
    perspective_polygon:
    - - 657
      - 736
    - - 899
      - 695
    - - 909
      - 754
    - - 671
      - 797
