game:
  boundaries:
    upper:
    - - 1
      - 1089
      - 439
      - 1113
    - - 439
      - 1113
      - 530
      - 1066
    - - 530
      - 1066
      - 1186
      - 941
    - - 1186
      - 941
      - 1647
      - 872
    - - 1647
      - 872
      - 2050
      - 850
    - - 2050
      - 850
      - 2535
      - 867
    - - 2535
      - 867
      - 3405
      - 911
    - - 3405
      - 911
      - 4243
      - 914
    - - 4243
      - 914
      - 4856
      - 925
    - - 4856
      - 925
      - 5278
      - 971
    - - 5278
      - 971
      - 5823
      - 1080
    - - 5823
      - 1081
      - 6174
      - 1162
    - - 6174
      - 1162
      - 6677
      - 1217
    - - 2560
      - 908
      - 2595
      - 910
    - - 2792
      - 940
      - 2826
      - 938
    - - 3312
      - 965
      - 3352
      - 963
    - - 3857
      - 966
      - 3898
      - 966
    - - 4381
      - 962
      - 4408
      - 960
    lower:
    - - 6
      - 913
      - 421
      - 900
    - - 421
      - 900
      - 439
      - 1111
    - - 439
      - 1113
      - 1276
      - 1420
    - - 1276
      - 1420
      - 2768
      - 1770
    - - 2768
      - 1770
      - 3951
      - 1807
    - - 3951
      - 1807
      - 5091
      - 1623
    - - 5091
      - 1623
      - 5804
      - 1387
    - - 5804
      - 1387
      - 6238
      - 1233
    - - 6238
      - 1233
      - 6285
      - 1022
    - - 6285
      - 1022
      - 6666
      - 1006
    - - 6614
      - 960
      - 6743
      - 944
  clip_box:
  - 266
  - 606
  - 6528
  - 2112
rink:
  scoreboard:
    projected_height: 110
    projected_width: 250
    perspective_polygon:
    - - 5751
      - 810
    - - 6059
      - 847
    - - 6052
      - 923
    - - 5743
      - 880
  end_zones:
    left_start:
    - - 1006
      - 1442
    - - 2519
      - 823
    left_stop:
    - - 1687
      - 1722
    - - 3030
      - 824
    right_start:
    - - 4316
      - 847
    - - 4880
      - 1910
    right_stop:
    - - 3682
      - 827
    - - 4053
      - 2117
