game:
  boundaries:
    upper:
    - - 22
      - 1286
      - 442
      - 1262
    - - 418
      - 1103
      - 442
      - 1262
    - - 418
      - 1103
      - 500
      - 1048
    - - 500
      - 1048
      - 988
      - 880
    - - 988
      - 880
      - 1395
      - 764
    - - 1395
      - 764
      - 1659
      - 710
    - - 1659
      - 710
      - 2015
      - 670
    - - 2015
      - 670
      - 2277
      - 646
    - - 2277
      - 646
      - 2556
      - 632
    - - 2556
      - 632
      - 2889
      - 602
    - - 2889
      - 602
      - 3275
      - 582
    - - 3275
      - 582
      - 3792
      - 556
    - - 3792
      - 556
      - 4231
      - 541
    - - 4231
      - 541
      - 4598
      - 559
    - - 4598
      - 562
      - 4851
      - 597
    - - 4851
      - 597
      - 5342
      - 716
    - - 5342
      - 716
      - 5584
      - 793
    - - 5584
      - 793
      - 5717
      - 880
    - - 5717
      - 880
      - 6134
      - 898
    - - 3985
      - 596
      - 4018
      - 594
    - - 3480
      - 628
      - 3515
      - 628
    - - 2523
      - 681
      - 2559
      - 684
    - - 2305
      - 684
      - 2356
      - 682
    lower:
    - - 10
      - 1051
      - 423
      - 1021
    - - 421
      - 1110
      - 423
      - 1021
    - - 421
      - 1110
      - 450
      - 1145
    - - 448
      - 1145
      - 868
      - 1266
    - - 868
      - 1266
      - 1903
      - 1497
    - - 1903
      - 1497
      - 2905
      - 1567
    - - 2905
      - 1567
      - 3994
      - 1436
    - - 3994
      - 1436
      - 4777
      - 1221
    - - 4777
      - 1221
      - 5418
      - 996
    - - 5418
      - 996
      - 5702
      - 892
    - - 5702
      - 892
      - 5723
      - 664
    - - 5723
      - 664
      - 6202
      - 661
  clip_box:
  - 106
  - 278
  - 5864
  - 2034
rink:
  scoreboard:
    projected_height: 150
    projected_width: 400
    perspective_polygon:
    - - 4939
      - 395
    - - 5177
      - 431
    - - 5168
      - 495
    - - 4933
      - 453
