game:
  boundaries:
    upper:
    - - 24
      - 1118
      - 410
      - 1130
    - - 410
      - 1130
      - 452
      - 1057
    - - 452
      - 1057
      - 1196
      - 810
    - - 1196
      - 810
      - 1563
      - 734
    - - 1563
      - 734
      - 2284
      - 644
    - - 2284
      - 644
      - 2370
      - 646
    - - 2370
      - 646
      - 3498
      - 591
    - - 3498
      - 591
      - 4017
      - 555
    - - 4017
      - 555
      - 4331
      - 544
    - - 4331
      - 544
      - 4848
      - 595
    - - 4848
      - 595
      - 5463
      - 766
    - - 5463
      - 766
      - 5685
      - 878
    - - 5685
      - 878
      - 6161
      - 865
    - - 2533
      - 681
      - 2569
      - 681
    - - 3011
      - 654
      - 3049
      - 654
    - - 3469
      - 635
      - 3530
      - 637
    lower:
    - - 17
      - 1042
      - 372
      - 1042
    - - 372
      - 1042
      - 431
      - 1029
    - - 414
      - 1122
      - 431
      - 1023
    - - 414
      - 1122
      - 1352
      - 1405
    - - 1352
      - 1405
      - 2975
      - 1571
    - - 2975
      - 1571
      - 4462
      - 1307
    - - 4462
      - 1307
      - 5447
      - 985
    - - 5447
      - 985
      - 5691
      - 867
    - - 5691
      - 867
      - 5738
      - 504
    - - 5738
      - 504
      - 6165
      - 454
  clip_box:
  - 106
  - 278
  - 5864
  - 2034
rink:
  scoreboard:
    projected_height: 150
    projected_width: 400
    perspective_polygon:
    - - 4939
      - 395
    - - 5177
      - 431
    - - 5168
      - 495
    - - 4933
      - 453
