game:
  boundaries:
    upper:
    - - 19
      - 1059
      - 390
      - 1064
    - - 390
      - 1064
      - 401
      - 1117
    - - 401
      - 1117
      - 534
      - 1015
    - - 534
      - 1015
      - 1315
      - 772
    - - 1315
      - 772
      - 1742
      - 688
    - - 1737
      - 686
      - 2192
      - 649
    - - 2192
      - 649
      - 2232
      - 669
    - - 2232
      - 669
      - 3870
      - 569
    - - 3870
      - 569
      - 3934
      - 543
    - - 3934
      - 543
      - 4462
      - 556
    - - 4462
      - 556
      - 4855
      - 602
    - - 4855
      - 602
      - 5332
      - 713
    - - 5332
      - 713
      - 5371
      - 750
    - - 5371
      - 750
      - 5590
      - 814
    - - 5590
      - 814
      - 5709
      - 865
    - - 5709
      - 717
      - 5709
      - 865
    - - 5709
      - 717
      - 5738
      - 998
    - - 5738
      - 998
      - 6142
      - 1024
    - - 5610
      - 947
      - 5649
      - 951
    - - 3980
      - 607
      - 4007
      - 605
    - - 3477
      - 633
      - 3519
      - 624
    - - 3002
      - 658
      - 3035
      - 655
    - - 2521
      - 686
      - 2569
      - 684
    - - 2298
      - 697
      - 2329
      - 699
    lower:
    - - 11
      - 934
      - 393
      - 993
    - - 393
      - 993
      - 408
      - 1119
    - - 408
      - 1119
      - 1176
      - 1349
    - - 1176
      - 1349
      - 2307
      - 1541
    - - 2307
      - 1541
      - 4217
      - 1366
    - - 4217
      - 1366
      - 5223
      - 1059
    - - 5223
      - 1059
      - 5610
      - 905
    - - 5610
      - 905
      - 5705
      - 883
    - - 5702
      - 563
      - 5705
      - 883
    - - 5702
      - 563
      - 6182
      - 571
    - - 5614
      - 794
      - 5654
      - 794
  clip_box:
  - 106
  - 278
  - 5864
  - 2034
rink:
  scoreboard:
    projected_height: 150
    projected_width: 400
    perspective_polygon:
    - - 4939
      - 395
    - - 5177
      - 431
    - - 5168
      - 495
    - - 4933
      - 453
