game:
  rink: sharks_black
  boundaries:
    upper:
    - - 6
      - 757
      - 397
      - 813
    - - 397
      - 813
      - 451
      - 751
    - - 451
      - 750
      - 939
      - 554
    - - 939
      - 554
      - 1174
      - 504
    - - 1174
      - 504
      - 1515
      - 475
    - - 1515
      - 475
      - 1535
      - 486
    - - 1535
      - 486
      - 2474
      - 484
    - - 2474
      - 484
      - 2516
      - 475
    - - 2516
      - 475
      - 2871
      - 496
    - - 2871
      - 496
      - 3178
      - 570
    - - 3178
      - 570
      - 3473
      - 683
    - - 3473
      - 683
      - 3650
      - 798
    - - 3650
      - 798
      - 4066
      - 814
    - - 1571
      - 496
      - 1581
      - 496
    - - 1693
      - 500
      - 1719
      - 502
    - - 2004
      - 500
      - 2015
      - 499
    - - 2312
      - 499
      - 2332
      - 498
    - - 2544
      - 502
      - 2615
      - 501
    - - 2617
      - 509
      - 2642
      - 508
    lower:
    - - 9
      - 743
      - 388
      - 803
    - - 388
      - 803
      - 658
      - 920
    - - 658
      - 920
      - 1529
      - 1142
    - - 1529
      - 1142
      - 2106
      - 1184
    - - 2106
      - 1184
      - 2805
      - 1094
    - - 2805
      - 1094
      - 3331
      - 948
    - - 3331
      - 948
      - 3633
      - 840
    - - 3631
      - 840
      - 3660
      - 761
    - - 3660
      - 761
      - 4073
      - 9
  clip_box:
  - 272
  - 334
  - 3764
  - 1296
rink:
  scoreboard:
    perspective_polygon:
    - - 571
      - 555
    - - 731
      - 504
    - - 745
      - 535
    - - 587
      - 593
