game:
  rink: sharks_black
  boundaries:
    upper:
    - - 2
      - 812
      - 133
      - 809
    - - 133
      - 809
      - 211
      - 730
    - - 211
      - 730
      - 542
      - 548
    - - 542
      - 548
      - 877
      - 396
    - - 877
      - 396
      - 1098
      - 328
    - - 1098
      - 328
      - 1409
      - 268
    - - 1409
      - 268
      - 1750
      - 235
    - - 1750
      - 235
      - 2124
      - 231
    - - 2124
      - 231
      - 2519
      - 259
    - - 2519
      - 259
      - 2942
      - 323
    - - 2942
      - 323
      - 3222
      - 405
    - - 3222
      - 405
      - 3429
      - 499
    - - 3429
      - 499
      - 3747
      - 663
    - - 3747
      - 663
      - 3852
      - 756
    - - 3852
      - 756
      - 4070
      - 753
    - - 1500
      - 288
      - 1522
      - 287
    - - 1695
      - 281
      - 1734
      - 278
    - - 2071
      - 267
      - 2101
      - 267
    - - 2440
      - 284
      - 2457
      - 285
    - - 2753
      - 320
      - 2784
      - 318
    lower:
    - - 5
      - 667
      - 120
      - 667
    - - 120
      - 667
      - 136
      - 817
    - - 136
      - 817
      - 550
      - 1052
    - - 549
      - 1052
      - 1249
      - 1350
    - - 2630
      - 1355
      - 3352
      - 1035
    - - 3352
      - 1035
      - 3844
      - 747
    - - 3832
      - 434
      - 3837
      - 748
    - - 3830
      - 434
      - 4079
      - 387
rink:
  scoreboard:
    perspective_polygon:
    - - 3572
      - 444
    - - 3736
      - 522
    - - 3716
      - 558
    - - 3555
      - 477
