rink:
  scoreboard:
    projected_height: 150
    projected_width: 400
    perspective_polygon:
    - - 862
      - 520
    - - 1106
      - 460
    - - 1118
      - 522
    - - 878
      - 586
game:
  clip_box:
  - 208
  - 388
  - 6016
  - 1702
  boundaries:
    upper:
    - - 7
      - 859
      - 344
      - 858
    - - 341
      - 858
      - 344
      - 987
    - - 344
      - 987
      - 412
      - 908
    - - 412
      - 908
      - 945
      - 719
    - - 945
      - 719
      - 1442
      - 584
    - - 1442
      - 584
      - 1863
      - 539
    - - 1863
      - 539
      - 2283
      - 516
    - - 2283
      - 516
      - 2313
      - 542
    - - 2313
      - 542
      - 3726
      - 598
    - - 3726
      - 598
      - 4080
      - 624
    - - 4080
      - 624
      - 4134
      - 609
    - - 4134
      - 609
      - 4733
      - 696
    - - 4733
      - 696
      - 5089
      - 779
    - - 5089
      - 779
      - 5476
      - 918
    - - 5476
      - 918
      - 5814
      - 1053
    - - 5814
      - 1053
      - 5928
      - 1179
    - - 5928
      - 1179
      - 6406
      - 1238
    - - 4200
      - 668
      - 4237
      - 670
    - - 3682
      - 636
      - 3717
      - 633
    - - 3167
      - 602
      - 3204
      - 602
    - - 2656
      - 587
      - 2706
      - 587
    - - 2404
      - 584
      - 2466
      - 581
    lower:
    - - 6
      - 699
      - 264
      - 716
    - - 264
      - 716
      - 345
      - 978
    - - 347
      - 979
      - 513
      - 1053
    - - 513
      - 1053
      - 1952
      - 1391
    - - 1951
      - 1393
      - 4154
      - 1482
    - - 4154
      - 1482
      - 5565
      - 1254
    - - 5565
      - 1254
      - 5879
      - 1170
    - - 5879
      - 1170
      - 5987
      - 1070
    - - 5987
      - 1070
      - 5988
      - 979
    - - 5988
      - 979
      - 6412
      - 908
