game:
  rink: sharks_gray
  boundaries:
    upper:
    - - 6
      - 732
      - 130
      - 811
    - - 130
      - 811
      - 266
      - 702
    - - 265
      - 702
      - 665
      - 488
    - - 665
      - 488
      - 968
      - 369
    - - 968
      - 369
      - 1233
      - 308
    - - 1233
      - 308
      - 1554
      - 261
    - - 1554
      - 261
      - 2264
      - 252
    - - 2264
      - 252
      - 2570
      - 277
    - - 2570
      - 277
      - 2972
      - 343
    - - 2972
      - 343
      - 3247
      - 431
    - - 3247
      - 431
      - 3390
      - 486
    - - 3390
      - 486
      - 3632
      - 604
    - - 3632
      - 604
      - 3826
      - 716
    - - 3826
      - 716
      - 3865
      - 750
    - - 3865
      - 750
      - 4074
      - 743
    - - 2444
      - 281
      - 2461
      - 284
    - - 2764
      - 320
      - 2780
      - 321
    - - 2081
      - 264
      - 2093
      - 265
    - - 1697
      - 280
      - 1727
      - 279
    - - 1497
      - 290
      - 1519
      - 290
    lower:
    - - 2
      - 556
      - 138
      - 818
    - - 138
      - 818
      - 652
      - 1099
    - - 652
      - 1099
      - 1257
      - 1357
    - - 2652
      - 1346
      - 2653
      - 1345
    - - 2665
      - 1349
      - 3385
      - 1021
    - - 3383
      - 1020
      - 3735
      - 823
    - - 3730
      - 821
      - 3867
      - 744
    - - 3863
      - 472
      - 3867
      - 744
    - - 3863
      - 472
      - 4076
      - 461
rink:
  scoreboard:
    projected_height: 150
    projected_width: 400
    perspective_polygon:
    - - 3572
      - 444
    - - 3736
      - 522
    - - 3716
      - 558
    - - 3555
      - 477
  camera:
    fixed_edge_rotation_angle: 55
    # sticky_size_ratio_to_frame_width: 10.0
    # sticky_translation_gaussian_mult: 10.0
    # unsticky_translation_size_ratio: 0.75
