game:
  name: "jrmocks"
  rink: "kissimmee"
  home: "Jr Mocks"
  away: "Cougars"
  clip_box: [null, 300, null, null]
  boundaries:
    upper:
      - [651, 1517, 2075, 1311]
      - [2064, 1334, 3188, 1300]
      - [3188, 1300, 4051, 1300]
      - [4051, 1300, 4763, 1317]
      - [4763, 1317, 5820, 1373]
      - [5809, 1345, 6488, 1412]
      - [6488, 1412, 7568, 1567]
    lower:
      - [28, 1272, 623, 1306]
      - [617, 1434, 1113, 2725]



