game:
  boundaries:
    upper:
    - - 7
      - 894
      - 202
      - 871
    - - 202
      - 871
      - 375
      - 690
    - - 373
      - 689
      - 973
      - 365
    - - 973
      - 365
      - 1341
      - 257
    - - 1341
      - 257
      - 1959
      - 224
    - - 1959
      - 224
      - 2617
      - 277
    - - 2617
      - 277
      - 3125
      - 375
    - - 3125
      - 375
      - 3485
      - 521
    - - 3485
      - 521
      - 3831
      - 730
    - - 3831
      - 730
      - 3993
      - 885
    - - 3993
      - 885
      - 4069
      - 864
    lower:
    - - 4
      - 809
      - 187
      - 802
    - - 185
      - 802
      - 218
      - 932
    - - 215
      - 932
      - 723
      - 1357
    - - 3412
      - 1362
      - 3500
      - 1293
    - - 3500
      - 1293
      - 3655
      - 1267
    - - 3655
      - 1267
      - 3898
      - 959
    - - 3898
      - 959
      - 4016
      - 846
    - - 4016
      - 846
      - 4056
      - 850
