game:
  name: "LA-2"
  rink: "vallco"
  boundaries:
    upper:
    - - 4
      - 879
      - 197
      - 889
    - - 197
      - 889
      - 301
      - 748
    - - 301
      - 748
      - 729
      - 479
    - - 729
      - 479
      - 1047
      - 334
    - - 1047
      - 334
      - 1421
      - 246
    - - 1421
      - 246
      - 2013
      - 209
    - - 2013
      - 209
      - 2569
      - 258
    - - 2569
      - 258
      - 3102
      - 367
    - - 3102
      - 367
      - 3408
      - 483
    - - 3408
      - 483
      - 3700
      - 650
    - - 3700
      - 650
      - 3975
      - 846
    - - 3975
      - 846
      - 3993
      - 881
    - - 3993
      - 881
      - 4071
      - 871
    lower:
    - - 4
      - 855
      - 210
      - 912
    - - 211
      - 912
      - 621
      - 1355
    - - 3567
      - 1356
      - 3962
      - 924
    - - 3962
      - 924
      - 4003
      - 849
    - - 4003
      - 849
      - 4062
      - 850
rink:
  scoreboard:
    perspective_polygon:
    - - 2344
      - 7
    - - 2546
      - 40
    - - 2518
      - 169
    - - 2328
      - 139
