rink:
  scoreboard:
    perspective_polygon:
    - - 402
      - 601
    - - 480
      - 567
    - - 504
      - 616
    - - 428
      - 656
game:
  boundaries:
    upper:
    - - 15
      - 935
      - 159
      - 902
    - - 159
      - 902
      - 203
      - 863
    - - 203
      - 863
      - 561
      - 665
    - - 561
      - 665
      - 840
      - 543
    - - 840
      - 543
      - 1062
      - 473
    - - 1062
      - 473
      - 1207
      - 438
    - - 1207
      - 438
      - 1619
      - 375
    - - 1619
      - 375
      - 1970
      - 351
    - - 1970
      - 351
      - 2323
      - 371
    - - 2323
      - 371
      - 2528
      - 408
    - - 2528
      - 408
      - 2804
      - 487
    - - 2804
      - 487
      - 3130
      - 636
    - - 3130
      - 636
      - 3226
      - 697
    - - 3226
      - 697
      - 3383
      - 694
    lower:
    - - 11
      - 848
      - 144
      - 840
    - - 144
      - 840
      - 450
      - 1362
    - - 3054
      - 1036
      - 3392
      - 351
