rink:
  scoreboard:
    perspective_polygon:
    - - 691
      - 1027
    - - 823
      - 965
    - - 865
      - 1055
    - - 732
      - 1119
    projected_height: 300
    projected_width: 400

    #
    # Configuration for breakaways
    #
    breakaway_detection:
      # Group velocities less than this are ignored
      min_considered_group_velocity: 2.0
      # What ratio of tracked players must be all reacting
      # to a breakaway?
      group_ratio_threshold: 0.3
      # What ratio of the group speed should we try to
      # apply within a single frame's speed adjustment?
      group_velocity_speed_ratio: 1.1
      # During a breakaway, what scale do we adjust the
      # maximum camera speed to allow for faster-than-normal tracking?
      scale_speed_constraints: 4.0
      # The number of frame steps to not allow any camera-stop conditions to
      # trigger such as cluster(s) direction change or "sticky translation" rules.
      # This is because the clusters may not have changed enough at the
      # beginning of a breakaway and may simply stop the camera movement
      # due to the cluster tracking rules.
      nonstop_delay_count: 2
      # When over-shooting the breakaway players, what scale do we apply
      # to the current speed each frame in order to slow it down?
      overshoot_scale_speed_ratio: 0.7

game:
  boundaries:
    upper:
    - - 14
      - 1590
      - 268
      - 1533
    - - 268
      - 1533
      - 866
      - 1193
    - - 866
      - 1193
      - 1363
      - 957
    - - 1363
      - 957
      - 1846
      - 800
    - - 1845
      - 800
      - 2535
      - 679
    - - 2535
      - 679
      - 3439
      - 602
    - - 3438
      - 602
      - 4003
      - 637
    - - 4003
      - 637
      - 4403
      - 718
    - - 4403
      - 718
      - 4821
      - 856
    - - 4821
      - 856
      - 5293
      - 1053
    - - 5293
      - 1053
      - 5803
      - 1365
    lower:
    - - 53
      - 1524
      - 255
      - 1522
    - - 255
      - 1522
      - 791
      - 2358
    - - 5240
      - 1756
      - 5533
      - 1175
    - - 5519
      - 862
      - 5813
      - 861
