rink:
  scoreboard:
    perspective_polygon:
    - - 691
      - 1027
    - - 823
      - 965
    - - 865
      - 1055
    - - 732
      - 1119
    projected_height: 300
    projected_width: 400
game:
  boundaries:
    upper:
    - - 14
      - 1590
      - 268
      - 1533
    - - 268
      - 1533
      - 866
      - 1193
    - - 866
      - 1193
      - 1363
      - 957
    - - 1363
      - 957
      - 1846
      - 800
    - - 1845
      - 800
      - 2535
      - 679
    - - 2535
      - 679
      - 3439
      - 602
    - - 3438
      - 602
      - 4003
      - 637
    - - 4003
      - 637
      - 4403
      - 718
    - - 4403
      - 718
      - 4821
      - 856
    - - 4821
      - 856
      - 5293
      - 1053
    - - 5293
      - 1053
      - 5803
      - 1365
    lower:
    - - 53
      - 1524
      - 255
      - 1522
    - - 255
      - 1522
      - 791
      - 2358
    - - 5240
      - 1756
      - 5533
      - 1175
    - - 5519
      - 862
      - 5813
      - 861
