game:
  name: "nm-wolves"
  rink: "arizona"
  home: "New Mexico Wolves"
  away: "Cougars"
  stitching:
  clip_box: null
  boundaries:
   upper:
      - [402, 947, 619, 808]
      - [614, 808, 1338, 509]
      - [1313, 519, 1687, 436]
      - [1686, 436, 2210, 381]
      - [2210, 381, 2873, 389]
      - [2865, 389, 3495, 451]
      - [3477, 449, 3997, 550]
      - [3997, 550, 4287, 639]
      - [4281, 635, 4550, 738]
      - [4550, 738, 5047, 973]
      - [5047, 973, 5237, 1093]
   lower:
      - [12, 826, 394, 791]
      - [350, 852, 590, 1173]
      - [590, 1173, 1254, 1902]
      - [4761, 1780, 5286, 1044]


