game:
  name: nm-wolves
  rink: arizona
  home: New Mexico Wolves
  away: Cougars
  stitching: null
  # clip_box: [null, 200, null, null]
  boundaries:
    upper:
    - - 402
      - 947
      - 619
      - 808
    - - 614
      - 808
      - 1338
      - 509
    - - 1313
      - 519
      - 1687
      - 436
    - - 1686
      - 436
      - 2210
      - 381
    - - 2210
      - 381
      - 2873
      - 389
    - - 2865
      - 389
      - 3495
      - 451
    - - 3477
      - 449
      - 3997
      - 550
    - - 3997
      - 550
      - 4287
      - 639
    - - 4281
      - 635
      - 4550
      - 738
    - - 4550
      - 738
      - 5047
      - 973
    - - 5047
      - 973
      - 5237
      - 1093
    - - 2370
      - 438
      - 2399
      - 435
    - - 2842
      - 448
      - 2876
      - 448
    - - 3296
      - 481
      - 3338
      - 481
    - [2042, 441, 2077, 441]
    - [2102, 431, 2125, 427]
    - [3578, 505, 3604, 508]
    - [3624, 517, 3656, 517]
    - [1006, 712, 1032, 708]
    - [4618, 853, 4638, 853]
    - [2885, 441, 2909, 440]
    - [1867, 452, 1897, 450]

    lower:
    - - 12
      - 826
      - 394
      - 791
    - - 350
      - 852
      - 590
      - 1173
    - - 590
      - 1173
      - 1254
      - 1902
    - - 4761
      - 1780
      - 5286
      - 1044

rink:
  tracking:
    cam_ignore_largest: true
  scoreboard:
    perspective_polygon:
    - - 586
      - 677
    - - 828
      - 581
    - - 851
      - 632
    - - 612
      - 732
  camera:
    fixed_edge_rotation_angle: 45
    follower_box_scale_width: 1.25
    follower_box_scale_height: 1.4
