game:
  name: "onehockey-sharksbb2"
  rink: "sharks_blacxk"
  home: "Cougars"
  away: "Sharks BB2"
  clip_box: [866, 605, 7920, 2438]
  boundaries:
    upper:
      - [3260, 1027, 4129, 1045]
      - [4107, 1035, 5233, 1159]
      - [7541, 1679, 8408, 1788]
    lower:
      - [1232, 1605, 1855, 1761]
      - [1805, 1770, 4063, 2127]
      - [4006, 2139, 6228, 2093]
      - [6168, 2115, 7543, 1818]
      - [7537, 1723, 8388, 1796]
