game:
  name: "onehockey-sharks10a"
  rink: "sharks_gray"
  home: "Cougars"
  away: "Sharks 10A"
  clip_box: [802, 512, 5547, 2000]
  boundaries:
    upper:
      - [1438, 995, 1952, 859]
      - [1924, 863, 2573, 802]
      - [986, 1201, 1132, 1072]
      - [1051, 1112, 1872, 851]
      - [2538, 799, 3461, 773]
      - [3456, 771, 4005, 803]
      - [3995, 791, 4579, 922]
      - [4465, 875, 4810, 1045]
      - [4742, 1017, 5128, 1313]
      - [5128, 1313, 5306, 1511]
    lower:
      - [254, 572, 996, 1196]
      - [972, 1235, 1629, 1533]
      - [1632, 1538, 2921, 1700]
      - [2876, 1695, 4512, 1652]
      - [4520, 1645, 5302, 1625]
      - [5302, 1626, 5339, 1566]
      - [5349, 1514, 5852, 1518]
