game:
  boundaries:
    upper:
    - - 288
      - 536
      - 413
      - 531
    - - 413
      - 531
      - 419
      - 436
    - - 410
      - 446
      - 669
      - 420
    - - 669
      - 420
      - 1112
      - 392
    - - 1112
      - 392
      - 1363
      - 380
    - - 1363
      - 380
      - 2216
      - 403
    - - 2216
      - 403
      - 2596
      - 393
    - - 2596
      - 393
      - 3204
      - 384
    - - 3204
      - 384
      - 3304
      - 384
    - - 3304
      - 384
      - 3483
      - 392
    - - 3483
      - 392
      - 3911
      - 412
    - - 3911
      - 412
      - 4079
      - 428
    - - 4079
      - 428
      - 4294
      - 429
    lower:
    - - 17
      - 436
      - 403
      - 438
    - - 403
      - 438
      - 422
      - 482
    - - 422
      - 482
      - 874
      - 1786
    - - 3604
      - 1792
      - 4003
      - 611
    - - 4003
      - 611
      - 4079
      - 402
    - - 4079
      - 402
      - 4211
      - 300
    - - 4208
      - 293
      - 4483
      - 270
rink:
  name: "vallco"
  scoreboard:
    perspective_polygon:
    - - 3822
      - 269
    - - 3927
      - 269
    - - 3926
      - 346
    - - 3822
      - 344
    projected_width: 700
    projected_height: 200
  tracking:
    cam_ignore_largest: true
  camera:
    fixed_edge_scaling_factor: 0.8
    follower_box_scale_width: 1.4
    follower_box_scale_height: 1.4
