game:
  boundaries:
    upper:
    - - 236
      - 1761
      - 464
      - 1763
    - - 468
      - 1763
      - 549
      - 1675
    - - 549
      - 1674
      - 823
      - 1475
    - - 823
      - 1475
      - 1151
      - 1266
    - - 1151
      - 1266
      - 1380
      - 1142
    - - 1380
      - 1142
      - 1659
      - 1010
    - - 1659
      - 1010
      - 2280
      - 802
    - - 2280
      - 802
      - 2913
      - 655
    - - 2913
      - 655
      - 3713
      - 671
    - - 3713
      - 671
      - 4218
      - 736
    - - 4161
      - 732
      - 4562
      - 848
    - - 4562
      - 848
      - 4960
      - 1019
    - - 4960
      - 1019
      - 5235
      - 1165
    - - 5235
      - 1165
      - 5304
      - 1210
    - - 5304
      - 1210
      - 5417
      - 1205
    lower:
    - - 280
      - 1635
      - 436
      - 1631
    - - 434
      - 1631
      - 549
      - 1814
    - - 549
      - 1814
      - 1286
      - 2289
    - - 3982
      - 2183
      - 4889
      - 1639
    - - 4889
      - 1639
      - 5050
      - 1419
    - - 5050
      - 1419
      - 5332
      - 1270
    - - 5340
      - 1168
      - 5428
      - 1165
rink:
  name: "vallco"
  scoreboard:
    projected_width: 500
    projected_height: 200
    perspective_polygon:
    - - 5117
      - 894
    - - 5254
      - 965
    - - 5209
      - 1053
    - - 5076
      - 982
