game:
  boundaries:
    upper:
    - - 28
      - 836
      - 650
      - 833
    - - 638
      - 684
      - 650
      - 833
    - - 638
      - 684
      - 1084
      - 647
    - - 1084
      - 647
      - 1644
      - 616
    - - 1644
      - 616
      - 2096
      - 605
    - - 2096
      - 605
      - 2668
      - 609
    - - 2668
      - 609
      - 3731
      - 631
    - - 3731
      - 631
      - 4559
      - 596
    - - 4559
      - 596
      - 4992
      - 592
    - - 4992
      - 592
      - 5272
      - 598
    - - 5272
      - 598
      - 6128
      - 650
    - - 6128
      - 650
      - 6349
      - 679
    - - 6349
      - 679
      - 6935
      - 700
    lower:
    - - 23
      - 547
      - 618
      - 561
    - - 618
      - 561
      - 1510
      - 2796
    - - 5576
      - 2790
      - 6350
      - 615
    - - 6350
      - 615
      - 6909
      - 70
rink:
  name: vallco
  scoreboard:
    perspective_polygon:
    - - 5923
      - 417
    - - 6080
      - 418
    - - 6081
      - 538
    - - 5923
      - 537
    projected_width: 700
    projected_height: 200
  tracking:
    cam_ignore_largest: true
  camera:
    fixed_edge_scaling_factor: 0.8
    follower_box_scale_width: 1.4
    follower_box_scale_height: 1.4
