game:
  boundaries:
    upper:
    - - 2
      - 547
      - 417
      - 540
    - - 416
      - 438
      - 417
      - 540
    - - 416
      - 438
      - 656
      - 415
    - - 656
      - 415
      - 1194
      - 388
    - - 1194
      - 388
      - 1568
      - 392
    - - 1568
      - 392
      - 2487
      - 404
    - - 2487
      - 404
      - 3099
      - 384
    - - 3099
      - 384
      - 3336
      - 383
    - - 3336
      - 383
      - 3883
      - 412
    - - 3883
      - 412
      - 4077
      - 434
    - - 4077
      - 434
      - 4371
      - 431
    lower:
    - - 3
      - 307
      - 399
      - 329
    - - 399
      - 329
      - 1012
      - 1759
    - - 3604
      - 1778
      - 4076
      - 361
    - - 4076
      - 361
      - 4418
      - 369
rink:
  name: vallco
  scoreboard:
    perspective_polygon:
    - - 3820
      - 270
    - - 3926
      - 271
    - - 3926
      - 348
    - - 3824
      - 344
    projected_width: 700
    projected_height: 200
  tracking:
    cam_ignore_largest: true
  camera:
    fixed_edge_scaling_factor: 0.8
    follower_box_scale_width: 1.4
    follower_box_scale_height: 1.4
