game:
  name: pdp_scrimmage_6_30
  rink: vallco
  boundaries:
    upper:
    - - 5
      - 873
      - 108
      - 877
    - - 108
      - 877
      - 308
      - 665
    - - 308
      - 665
      - 712
      - 369
    - - 712
      - 369
      - 1098
      - 185
    - - 1098
      - 185
      - 1634
      - 57
    - - 1634
      - 57
      - 2069
      - 36
    - - 2069
      - 36
      - 2936
      - 262
    - - 2936
      - 262
      - 3300
      - 436
    - - 3300
      - 436
      - 3520
      - 594
    - - 3520
      - 594
      - 3909
      - 945
    - - 3909
      - 945
      - 4068
      - 1147
    - - 4068
      - 1147
      - 4097
      - 1132
    lower:
    - - 4
      - 830
      - 101
      - 818
    - - 102
      - 871
      - 219
      - 1178
    - - 219
      - 1178
      - 458
      - 1288
    - - 458
      - 1288
      - 1037
      - 1796
    - - 3479
      - 1797
      - 3752
      - 1558
    - - 3752
      - 1558
      - 4067
      - 1143
    - - 4065
      - 883
      - 4093
      - 880
rink:
  camera:
    fixed_edge_rotation_angle: 45
