game:
  name: "pdp_+scrimmage_1"
  rink: "vallco"
  boundaries:
    upper:
    - - 25
      - 1010
      - 114
      - 976
    - - 114
      - 976
      - 295
      - 794
    - - 295
      - 794
      - 711
      - 478
    - - 711
      - 478
      - 1086
      - 282
    - - 1086
      - 282
      - 1630
      - 124
    - - 1630
      - 125
      - 2146
      - 71
    - - 2146
      - 71
      - 2673
      - 160
    - - 2673
      - 160
      - 3116
      - 304
    - - 3116
      - 304
      - 3391
      - 445
    - - 3391
      - 445
      - 3646
      - 618
    - - 3646
      - 618
      - 3914
      - 854
    - - 3916
      - 855
      - 4055
      - 1013
    - - 4053
      - 1011
      - 4090
      - 1038
    lower:
    - - 6
      - 954
      - 103
      - 957
    - - 103
      - 957
      - 397
      - 1556
    - - 397
      - 1556
      - 655
      - 1792
    - - 3301
      - 1795
      - 3482
      - 1527
    - - 3482
      - 1527
      - 3792
      - 1580
    - - 3792
      - 1580
      - 4071
      - 1048
    - - 4076
      - 833
      - 4093
      - 834
rink:
  scoreboard:
    perspective_polygon:
    - - 3921
      - 561
    - - 4010
      - 639
    - - 3974
      - 767
    - - 3881
      - 682
  camera:
    fixed_edge_rotation_angle: 40
