game:
  name: "pdp_scrimmage_6_30"
  rink: "vallco"
  boundaries:
    upper:
    - - 4
      - 899
      - 112
      - 894
    - - 111
      - 893
      - 209
      - 761
    - - 209
      - 761
      - 451
      - 557
    - - 451
      - 557
      - 777
      - 325
    - - 777
      - 325
      - 1126
      - 179
    - - 1126
      - 179
      - 1607
      - 66
    - - 1607
      - 66
      - 1953
      - 29
    - - 1953
      - 29
      - 2146
      - 41
    - - 2146
      - 41
      - 2556
      - 132
    - - 2556
      - 132
      - 3036
      - 305
    - - 3036
      - 305
      - 3305
      - 443
    - - 3305
      - 443
      - 3552
      - 619
    - - 3552
      - 619
      - 3774
      - 814
    - - 3774
      - 814
      - 4002
      - 1055
    - - 4002
      - 1055
      - 4069
      - 1141
    - - 4069
      - 1141
      - 4093
      - 1140
    lower:
    - - 5
      - 807
      - 87
      - 814
    - - 87
      - 814
      - 281
      - 1330
    - - 283
      - 1331
      - 642
      - 1807
    - - 3710
      - 1793
      - 3983
      - 1379
    - - 3982
      - 1377
      - 4070
      - 1131
    - - 4060
      - 980
      - 4086
      - 980

rink:
  camera:
    fixed_edge_rotation_angle: 40
