game:
  name: "queens"
  rink: "orlando_ice_den"
  home: "Queens Something"
  away: "Cougars"
  clip_box: null
  boundaries:
   upper:
      - [647, 1358, 862, 1114]
      - [862, 1114, 1630, 571]
      - [1522, 625, 2219, 367]
      - [2143, 376, 2856, 272]
      - [2855, 272, 3634, 247]
      - [3550, 246, 4316, 353]
      - [4292, 351, 4909, 550]
      - [4912, 549, 5283, 748]
      - [5265, 733, 6036, 1390]
   lower:
      - [0, 1225, 641, 1192]
      - [584, 1325, 645, 1324]
      - [628, 1362, 1400, 2307]
      - [5454, 2208, 6061, 1405]
      - [6044, 1402, 6367, 1434]
