game:
  name: sharks-bb1-2
  rink: sharks_black
  home: Cougars
  away: Sharks 10BB-1
  stitching:
    offsets:
    - 2.06935921221635
    - 0
  _boundaries:
    upper:
    - - 937
      - 1333
      - 1670
      - 1150
    - - 1670
      - 1150
      - 2238
      - 1065
    - - 2236
      - 1065
      - 2943
      - 1059
    - - 2943
      - 1059
      - 3567
      - 1061
    - - 3567
      - 1061
      - 4497
      - 1075
    - - 4497
      - 1075
      - 5530
      - 1118
    - - 5530
      - 1118
      - 6113
      - 1215
    - - 6113
      - 1215
      - 6940
      - 1452
    - - 6940
      - 1452
      - 7187
      - 1593
    - - 7182
      - 1595
      - 7811
      - 1627
    - - 3012
      - 1108
      - 3047
      - 1102
    - - 3250
      - 1130
      - 3299
      - 1130
    - - 3824
      - 1118
      - 3874
      - 1120
    - - 4413
      - 1142
      - 4470
      - 1137
    - - 5013
      - 1146
      - 5063
      - 1145
    lower:
    - - 26
      - 1318
      - 928
      - 1326
    - - 928
      - 1326
      - 999
      - 1571
    - - 997
      - 1571
      - 1926
      - 1901
    - - 1926
      - 1901
      - 3125
      - 2145
    - - 3125
      - 2145
      - 4707
      - 2200
    - - 4707
      - 2200
      - 6070
      - 1986
    - - 6070
      - 1986
      - 7174
      - 1638
    - - 7174
      - 1638
      - 7343
      - 1414
    - - 7219
      - 1351
      - 7724
      - 1323
  _clip_box:
  - 576
  - 822
  - 7480
  - 2526
rink:
  tracking:
    cam_ignore_largest: true
  camera:
    fixed_edge_rotation_angle: 35
    follower_box_scale_width: 1.25
    follower_box_scale_height: 1.25
  scoreboard:
    projected_height: 150
    projected_width: 400
    perspective_polygon:
    - - 1142
      - 1015
    - - 1441
      - 958
    - - 1452
      - 1027
    - - 1157
      - 1092
  ice_contours_mask_count: 1
  ice_contours_mask_centroid:
  - 3988.456298828125
  - 1613.1497802734375
