game:
  name: "sharks-bb3-1"
  rink: "sharks_orange"
  home: "Cougars"
  away: "Sharks 10BB-3"

  stitching:
    offsets: [2.4975024975024973, 0]

  clip_box: [1090, 0, 8716, 2200]
  boundaries:
    upper:
      - [1225, 1549, 1348, 1393]
      - [1318, 1413, 2086, 1009]
      - [2060, 1001, 2640, 790]
      - [2520, 819, 3548, 596]
      - [3529, 602, 4766, 435]
      - [4670, 451, 5645, 377]
      - [5569, 385, 6518, 367]
      - [6490, 367, 7235, 387]
      - [7086, 391, 7867, 517]
      - [7861, 511, 8576, 720]
      - [8562, 720, 8632, 776]
      - [8614, 656, 9740, 740]
      # False detections
      - [4051, 578, 4096, 578]
      - [4746, 499, 4802, 499]
      - [5487, 437, 5543, 439]
       # Door (false detection)
      - [8285, 927, 8401, 927]
    lower:
      - [59, 1387, 1211, 1369]
      - [1247, 1553, 2721, 1547]
      - [2717, 1547, 4955, 1495]
      - [4947, 1499, 7157, 1001]
      - [7157, 1001, 8369, 813]
      - [8369, 813, 8608, 772]
      - [8612, 586, 9812, 618]


rink:
  tracking:
    cam_ignore_largest: true

  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 40

#
# Model config
#
model:
  tracker:
    type: fair
    conf_thres: 0.25


#
# Problems
#
# Bad tracking to right at 25:40
# also: 18:50

