game:
  name: "sharks-bb1-2"
  rink: "sharks_black"
  home: "Cougars"
  away: "Sharks 10BB-1"

  stitching:
    offsets: null

  boundaries:
    upper:
      - [954, 1300, 1859, 1079]
      - [1859, 1079, 2307, 1029]
      - [2244, 1033, 3196, 1009]
      - [3148, 1013, 3962, 1017]
      - [3949, 1017, 4874, 1045]
      - [4848, 1045, 5710, 1113]
      - [6758, 1388, 7124, 1546]
      - [7115, 1493, 7861, 1493]
    lower:
      - [1016, 1528, 1833, 1832]
      - [1817, 1837, 2926, 2082]
      - [2897, 2079, 3881, 2181]
      - [3855, 2183, 4858, 2147]
      - [4858, 2147, 5942, 1960]
      - [5941, 1960, 6987, 1644]
      - [6966, 1644, 7121, 1588]
      - [7167, 711, 7941, 674]
      - [10, 1536, 998, 1455]

  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 35
