game:
  name: "sharks-bb2-2"
  rink: "vallco"
  home: "Cougars"
  away: "Sharks 10BB-2"

  stitching:
    offsets: null

  boundaries:
    upper:
    lower:
rink:
  tracking:
    #
    # Some tracking config
    #
    cam_ignore_largest: true

  camera:
    #
    # Rink-related tracking config
    #
    fixed_edge_rotation_angle: 40
    follower_box_scale_width: 1.2
    follower_box_scale_height: 1.2
