game:
  name: sharks-bb3-2
  rink: sharks_orange
  home: Cougars
  away: Sharks 10BB-3
  stitching:
    offsets:
    - 2.4975024975024973
    - 0
  boundaries:
    upper:
    - - 10
      - 1208
      - 230
      - 1195
    - - 231
      - 1194
      - 380
      - 1108
    - - 380
      - 1108
      - 903
      - 894
    - - 905
      - 894
      - 1196
      - 805
    - - 1196
      - 805
      - 1736
      - 668
    - - 1736
      - 668
      - 2133
      - 580
    - - 2136
      - 580
      - 2556
      - 501
    - - 2556
      - 501
      - 2875
      - 461
    - - 2875
      - 461
      - 3200
      - 449
    - - 3200
      - 449
      - 3509
      - 492
    - - 3509
      - 492
      - 3909
      - 596
    - - 3909
      - 596
      - 4012
      - 670
    - - 4012
      - 670
      - 4499
      - 658
    - - 2392
      - 587
      - 2409
      - 579
    - - 2713
      - 514
      - 2737
      - 514
    - - 1739
      - 716
      - 1773
      - 709
    - - 1576
      - 740
      - 1607
      - 737
    - - 2071
      - 637
      - 2094
      - 634
    - - 726
      - 1446
      - 830
      - 1422
    lower:
    - - 8
      - 1136
      - 204
      - 1136
    - - 204
      - 1136
      - 229
      - 1221
    - - 229
      - 1218
      - 675
      - 1306
    - - 675
      - 1306
      - 1415
      - 1359
    - - 1397
      - 1356
      - 2225
      - 1231
    - - 2225
      - 1231
      - 3089
      - 1006
    - - 3089
      - 1006
      - 3617
      - 812
    - - 3617
      - 812
      - 3993
      - 662
    - - 3997
      - 660
      - 4507
      - 352
rink:
  tracking:
    cam_ignore_largest: false
  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: [40, 15]
  scoreboard:
    perspective_polygon:
    - - 3679
      - 360
    - - 3880
      - 404
    - - 3873
      - 452
    - - 3674
      - 412
model:
  tracker:
    type: fair
