game:
  name: "sharks-bb3-1"
  rink: "sharks_orange"
  home: "Cougars"
  away: "Sharks 10BB-3"

  stitching:
    offsets: [2.4975024975024973, 0]

  clip_box: null
  boundaries:
    upper:
      - [975, 969, 1585, 660]
      - [1581, 660, 1897, 548]
      - [1897, 548, 2476, 422]
      - [2472, 428, 3276, 329]
      - [3276, 329, 3878, 280]
      - [3863, 278, 4492, 256]
      - [4487, 256, 4990, 276]
      - [4983, 276, 5332, 331]
      - [5332, 331, 5983, 493]
      - [5983, 493, 6873, 479]
      - [860, 1085, 970, 967]
      # False detections
      - [2627, 434, 2663, 436]
      - [3330, 354, 3368, 354]
      - [2843, 414, 2879, 414]
      - [3855, 318, 3886, 318]
      - [5817, 658, 5866, 662]

    lower:
      - [13, 1075, 866, 939]
      - [874, 1091, 1615, 1082]
      - [1615, 1082, 3208, 1050]
      - [3210, 1055, 3492, 1050]
      - [3465, 1045, 4666, 772]
      - [4659, 772, 5806, 581]
      - [5806, 581, 6030, 551]
      - [6036, 354, 6861, 364]

rink:
  tracking:
    cam_ignore_largest: true

  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 40
