game:
  name: "sharks-bb1-2"
  rink: "sharks_black"
  home: "Cougars"
  away: "Sharks 10BB-1"

  stitching:
    offsets: null

  boundaries:
    upper:
    lower:

  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 35

