game:
  name: "sharks-bb2-2"
  rink: "vallco"
  home: "Cougars"
  away: "Sharks 10BB-2"

  stitching:
    offsets: null

  boundaries:
    upper:
      - [179, 1493, 485, 1324]
      - [422, 1357, 1142, 1055]
      - [1128, 1049, 2480, 619]
      - [2447, 617, 4224, 621]
      - [4195, 614, 5447, 968]
      - [5498, 1069, 5620, 1055]
    lower:
      - [5, 1498, 170, 1491]
      - [154, 1481, 601, 2117]
      - [4831, 2037, 5586, 926]
rink:
  tracking:
    #
    # Some tracking config
    #
    cam_ignore_largest: true

  camera:
    #
    # Rink-related tracking config
    #
    fixed_edge_rotation_angle: 40
    follower_box_scale_width: 1.35
    follower_box_scale_height: 1.35
