game:
  name: "sharks-bb3-2"
  rink: "sharks_orange"
  home: "Cougars"
  away: "Sharks 10BB-3"

  stitching:
    offsets: [2.4975024975024973, 0]

  boundaries:
    upper:
      - [154, 1535, 251, 1438]
      - [242, 1442, 819, 1103]
      - [806, 1108, 1429, 851]
      - [1412, 855, 1971, 716]
      - [1954, 716, 2808, 571]
      - [2796, 566, 3674, 458] # high one left of center
      - [3666, 462, 4469, 407]
      - [4463, 405, 5494, 381]
      - [5493, 380, 6041, 403]
      - [5966, 403, 6597, 498]
      - [6597, 494, 7071, 601]
      - [7068, 593, 7469, 722]
      - [7447, 714, 7619, 835]

      # False detections
      - [2672, 623, 2709, 621]
      - [2969, 595, 3004, 587]
      - [3677, 514, 3722, 511]
      - [4419, 450, 4458, 450]
      # Door (false detection)

    lower:
      - [154, 1535, 251, 1438]
      - [0, 1493, 159, 1474]
      - [157, 1479, 180, 1570]
      - [185, 1564, 2166, 1543]
      - [2166, 1543, 3879, 1487]
      - [3872, 1487, 5615, 1130]
      - [5615, 1130, 6758, 904]
      - [6758, 904, 7544, 771]
      - [7523, 604, 7619, 598]

rink:
  tracking:
    cam_ignore_largest: false

  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 35

#
# Model config
#
model:
  tracker:
    type: fair
    # conf_thres: 0.25
#
# Problems
#
# Bad tracking to right at 25:40
# also: 18:50

