game:
  name: "sharks-bb3-1"
  rink: "sharks_orange"
  home: "Cougars"
  away: "Sharks 10BB-3"

  stitching:
    offsets: [2.4975024975024973, 0]

  #clip_box: [1090, 0, 8716, 2200]
  boundaries:
    - [154, 1535, 251, 1438]
  upper:
    - [242, 1442, 819, 1103]
    - [806, 1108, 1429, 841]
    - [1412, 845, 1971, 706]
    - [1954, 706, 2808, 561]
    - [2796, 556, 3674, 448] # high one left of center
    - [3666, 452, 4469, 397]
    - [4463, 395, 5494, 371]
    - [5493, 370, 6041, 393]
    - [5966, 393, 6597, 488]
    - [6597, 484, 7071, 591]
    - [7068, 583, 7469, 712]
    - [7447, 704, 7619, 825]

    # False detections
    - [2672, 623, 2709, 621]
    - [2969, 595, 3004, 587]
    - [3677, 514, 3722, 511]
    - [4419, 450, 4458, 450]
    # Door (false detection)

  lower:
    - [154, 1535, 251, 1438]
    - [0, 1493, 159, 1474]
    - [157, 1479, 180, 1570]
    - [185, 1564, 2166, 1543]
    - [2166, 1543, 3879, 1487]
    - [3872, 1487, 5615, 1130]
    - [5615, 1130, 6758, 904]
    - [6758, 904, 7544, 771]
    - [7523, 604, 7619, 598]

rink:
  tracking:
    cam_ignore_largest: true

  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 40

#
# Model config
#
model:
  tracker:
    type: fair
    conf_thres: 0.25
#
# Problems
#
# Bad tracking to right at 25:40
# also: 18:50

