game:
  name: sharks-bb3-2
  rink: sharks_orange
  home: Cougars
  away: Sharks 10BB-3
  stitching:
    offsets:
    - 2.4975024975024973
    - 0
  boundaries:
    upper:
    - - 2793
      - 1319
      - 2834
      - 1314
    - - 3060
      - 1266
      - 3118
      - 1262
    - - 3644
      - 1123
      - 3690
      - 1123
    - - 4203
      - 1017
      - 4257
      - 1018
    - - 4786
      - 917
      - 4846
      - 911
    - - 26
      - 2179
      - 397
      - 2113
    - - 393
      - 2107
      - 619
      - 1984
    - - 619
      - 1984
      - 1474
      - 1630
    - - 1474
      - 1630
      - 1852
      - 1494
    - - 1852
      - 1494
      - 2679
      - 1271
    - - 2679
      - 1271
      - 3527
      - 1074
    - - 3529
      - 1071
      - 4500
      - 895
    - - 4500
      - 895
      - 5258
      - 797
    - - 5258
      - 797
      - 5913
      - 827
    - - 5913
      - 827
      - 6466
      - 935
    - - 6466
      - 935
      - 6995
      - 1110
    - - 6995
      - 1110
      - 7928
      - 1131
    lower:
    - - 12
      - 2007
      - 383
      - 2067
    - - 383
      - 2067
      - 412
      - 2140
    - - 412
      - 2140
      - 1291
      - 2323
    - - 1291
      - 2323
      - 2447
      - 2393
    - - 2447
      - 2393
      - 3685
      - 2222
    - - 3685
      - 2222
      - 5260
      - 1829
    - - 5260
      - 1829
      - 6237
      - 1508
    - - 6237
      - 1508
      - 6916
      - 1232
    - - 6916
      - 1232
      - 7047
      - 1170
    - - 7047
      - 1170
      - 7319
      - 690
    - - 7319
      - 690
      - 7976
      - 639
rink:
  tracking:
    cam_ignore_largest: true
  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle:
    - 40
    - 15
  scoreboard:
    perspective_polygon:
    - - 483
      - 1654
    - - 807
      - 1541
    - - 838
      - 1620
    - - 513
      - 1739
    projected_width: 400
    projected_height: 100
model:
  tracker:
    type: fair
