game:
  name: "sharks-bb3-1"
  rink: "vallco"
  home: "Cougars"
  away: "Sharks 10BB-3"

  stitching:
    offsets: [-15.82431174267909, 0.0]

  clip_box: null
  boundaries:
    upper:
    lower:
rink:
  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 40
