game:
  boundaries:
    upper:
    - - 1
      - 1073
      - 547
      - 741
    - - 547
      - 741
      - 1170
      - 502
    - - 1170
      - 502
      - 1919
      - 375
    - - 1919
      - 375
      - 2649
      - 408
    - - 2649
      - 408
      - 2925
      - 432
    - - 2925
      - 432
      - 3692
      - 419
    - - 3692
      - 419
      - 4383
      - 539
    - - 4383
      - 539
      - 4981
      - 767
    - - 4981
      - 767
      - 5435
      - 1033
    - - 5435
      - 1033
      - 5903
      - 1364
    - - 5903
      - 1364
      - 6031
      - 1486
    lower:
    - - 4
      - 1545
      - 844
      - 2488
    - - 5386
      - 2477
      - 6028
      - 1517
rink:
  scoreboard:
    perspective_polygon:
    - - 178
      - 688
    - - 336
      - 609
    - - 373
      - 696
    - - 224
      - 781
    projected_height: 300
    projected_width: 300
