game:
  boundaries:
    upper:
    - - 7
      - 1115
      - 489
      - 1057
    - - 489
      - 1057
      - 943
      - 840
    - - 943
      - 840
      - 1338
      - 689
    - - 1338
      - 689
      - 1911
      - 537
    - - 1909
      - 537
      - 2283
      - 475
    - - 2283
      - 475
      - 2721
      - 442
    - - 2721
      - 442
      - 3294
      - 436
    - - 3293
      - 436
      - 3820
      - 452
    - - 3814
      - 445
      - 4369
      - 520
    - - 4369
      - 520
      - 4823
      - 631
    - - 4823
      - 632
      - 5186
      - 760
    - - 5186
      - 760
      - 5542
      - 911
    - - 5540
      - 912
      - 5823
      - 1046
    - - 5823
      - 1046
      - 5903
      - 1105
    - - 5897
      - 1105
      - 6146
      - 1095
    lower:
    - - 6
      - 909
      - 443
      - 881
    - - 443
      - 881
      - 504
      - 1080
    - - 504
      - 1080
      - 814
      - 1415
    - - 814
      - 1415
      - 1515
      - 2058
    - - 5422
      - 1940
      - 5900
      - 1096
    - - 5903
      - 954
      - 6191
      - 938
rink:
  scoreboard:
    perspective_polygon:
    - - 947
      - 585
    - - 1089
      - 537
    - - 1125
      - 629
    - - 981
      - 682
