game:
  boundaries:
    upper:
    - - 88
      - 1215
      - 679
      - 1185
    - - 662
      - 1180
      - 920
      - 1043
    - - 910
      - 1043
      - 1635
      - 731
    - - 1634
      - 732
      - 2085
      - 607
    - - 2083
      - 607
      - 2524
      - 522
    - - 2522
      - 522
      - 3204
      - 472
    - - 3204
      - 472
      - 3880
      - 476
    - - 3880
      - 476
      - 4350
      - 519
    - - 4350
      - 519
      - 4865
      - 619
    - - 4865
      - 619
      - 5282
      - 752
    - - 5282
      - 752
      - 5624
      - 894
    - - 5624
      - 894
      - 6054
      - 1088
    - - 6054
      - 1088
      - 6385
      - 1282
    - - 6384
      - 1283
      - 6626
      - 1254
    lower:
    - - 61
      - 1124
      - 653
      - 1090
    - - 652
      - 1159
      - 1782
      - 2283
    - - 5817
      - 2188
      - 6387
      - 1242
    - - 6399
      - 1018
      - 6633
      - 1002
rink:
  scoreboard:
    perspective_polygon:
    - - 1136
      - 665
    - - 1289
      - 607
    - - 1330
      - 708
    - - 1178
      - 768
    projected_height: 300
    projected_width: 300
