rink:
  tracking:
    #
    # Some tracking config
    #
    cam_ignore_largest: true

game:
  boundaries:
    upper:
    - - 163
      - 1057
      - 319
      - 991
    - - 314
      - 989
      - 978
      - 839
    - - 976
      - 839
      - 1316
      - 794
    - - 1316
      - 794
      - 1924
      - 764
    - - 1924
      - 764
      - 2812
      - 792
    - - 2812
      - 792
      - 3547
      - 866
    - - 3547
      - 866
      - 3927
      - 942
    - - 3927
      - 942
      - 4524
      - 1091
    - - 4524
      - 1091
      - 4803
      - 1217
    lower:
    - - 166
      - 1077
      - 896
      - 1272
    - - 889
      - 1274
      - 2185
      - 1411
    - - 2180
      - 1407
      - 3394
      - 1403
    - - 3395
      - 1403
      - 4206
      - 1275
    - - 4206
      - 1275
      - 4989
      - 1004
    - - 4
      - 1014
      - 176
      - 1037
