game:
  name: "sundevils"
  rink: "gilbert"
  home: "Sun Devils"
  away: "Cougars"
  boundaries:
    upper:
      - [448, 1034, 519, 963]
      - [512, 956, 1291, 728]
      - [1207, 760, 1646, 696]
      - [1632, 693, 2201, 707]
      - [2204, 696, 2801, 735]
      - [2801, 735, 3419, 805]
      - [3419, 805, 3907, 858]
      - [3907, 858, 4294, 967]
    lower:
      - [463, 1034, 1284, 1350]
      - [1267, 1350, 2426, 1627]
      - [2426, 1627, 3388, 1680]
      - [3388, 1680, 4406, 1497]
      - [4396, 1480, 5028, 1279]
      - [5049, 1051, 5354, 1002]
      - [10, 791, 469, 816]




