game:
  name: "sundevils"
  rink: "gilbert"
  home: "Sun Devils"
  away: "Cougars"
  boundaries:
    upper:
      - [450, 1015, 609, 926]
      - [583, 941, 1291, 743]
      - [1276, 740, 1686, 696]
      - [1695, 702, 2076, 699]
      - [2081, 693, 2669, 725]
      - [2663, 719, 3291, 778]
      - [3288, 781, 3849, 867]
      - [3849, 867, 4144, 938]
      - [4144, 926, 4336, 982]
      - [4336, 982, 4932, 1200]
    lower:
      - [338, 914, 456, 896]
      - [453, 1006, 795, 1174]
      - [786, 1171, 1775, 1487]
      - [1778, 1490, 2757, 1658]
      - [2754, 1667, 3598, 1664]
      - [3583, 1658, 4374, 1534]
      - [4138, 1557, 5015, 1298]
      - [5020, 1221, 5156, 1227]




