game:
  boundaries:
    upper:
    - - 236
      - 1761
      - 464
      - 1763
    - - 468
      - 1763
      - 549
      - 1675
    - - 549
      - 1674
      - 823
      - 1475
    - - 823
      - 1475
      - 1151
      - 1266
    - - 1151
      - 1266
      - 1380
      - 1142
    - - 1380
      - 1142
      - 1659
      - 1010
    - - 1659
      - 1010
      - 2280
      - 802
    - - 2280
      - 802
      - 2913
      - 655
    - - 2913
      - 655
      - 3713
      - 671
    - - 3713
      - 671
      - 4218
      - 736
    - - 4161
      - 732
      - 4562
      - 848
    - - 4562
      - 848
      - 4960
      - 1019
    - - 4960
      - 1019
      - 5235
      - 1165
    - - 5235
      - 1165
      - 5304
      - 1210
    - - 5304
      - 1210
      - 5417
      - 1205
    lower:
    - - 280
      - 1635
      - 436
      - 1631
    - - 434
      - 1631
      - 549
      - 1814
    - - 549
      - 1814
      - 1286
      - 2289
    - - 3982
      - 2183
      - 4889
      - 1639
    - - 4889
      - 1639
      - 5050
      - 1419
    - - 5050
      - 1419
      - 5332
      - 1270
    - - 5340
      - 1168
      - 5428
      - 1165
rink:
  name: "vallco"
  scoreboard:
    projected_width: 500
    projected_height: 200
  camera:
    fixed_edge_scaling_factor: 0.8
    # fixed_edge_rotation_angle: 40
    fixed_edge_rotation_angle: null
    follower_box_scale_width: 1.6
    follower_box_scale_height: 1.6
    #
    # Configuration for breakaways
    #
    breakaway_detection:
      # When over-shooting the breakaway players, what scale do we apply
      # to the current speed each frame in order to slow it down?
      overshoot_scale_speed_ratio: 0.2
      scale_speed_constraints: 1.0

