game:
  boundaries:
    upper:
    - - 46
      - 2600
      - 888
      - 1499
    - - 888
      - 1499
      - 922
      - 1337
    - - 922
      - 1337
      - 1750
      - 1138
    - - 1750
      - 1138
      - 2593
      - 1046
    - - 2593
      - 1046
      - 3060
      - 1079
    - - 3062
      - 1081
      - 4741
      - 1090
    - - 4741
      - 1090
      - 4838
      - 1065
    - - 4838
      - 1065
      - 5834
      - 1159
    - - 5834
      - 1159
      - 6182
      - 1228
    - - 6182
      - 1228
      - 6932
      - 1434
    - - 6932
      - 1434
      - 7184
      - 1641
    - - 7184
      - 1641
      - 7945
      - 1723
    - - 5033
      - 1136
      - 5064
      - 1132
    - - 3823
      - 1111
      - 3855
      - 1111
    - - 4402
      - 1125
      - 4425
      - 1125
    - - 3238
      - 1105
      - 3303
      - 1115
    lower:
    - - 35
      - 1285
      - 934
      - 1348
    - - 934
      - 1348
      - 1014
      - 1587
    - - 1014
      - 1587
      - 2058
      - 1929
    - - 2058
      - 1929
      - 3662
      - 2205
    - - 3662
      - 2205
      - 5517
      - 2107
    - - 5517
      - 2107
      - 6727
      - 1784
    - - 6727
      - 1784
      - 7177
      - 1606
    - - 7179
      - 1606
      - 7261
      - 834
    - - 7261
      - 830
      - 7921
      - 788
rink:
  name: vallco
  scoreboard:
    projected_width: 500
    projected_height: 200
  camera:
    fixed_edge_scaling_factor: 0.8
    fixed_edge_rotation_angle: null
    follower_box_scale_width: 1.6
    follower_box_scale_height: 1.6
    breakaway_detection:
      overshoot_scale_speed_ratio: 0.2
      scale_speed_constraints: 1.0
  end_zones:
    left_start:
    - !!python/tuple
      - 1487
      - 1746
    - !!python/tuple
      - 3004
      - 1060
    left_stop:
    - !!python/tuple
      - 1778
      - 1877
    - !!python/tuple
      - 3304
      - 1088
    right_start:
    - !!python/tuple
      - 4690
      - 1051
    - !!python/tuple
      - 6121
      - 2014
    right_stop:
    - !!python/tuple
      - 4390
      - 1044
    - !!python/tuple
      - 5650
      - 2253
