game:
  name: "tvbb2"
  rink: "dublin"
  home: "Blue Devils"
  away: "Cougars"
  clip_box: [50, 360, 3928, 1557]
  boundaries:
    upper:
      -  [214, 753, 1265, 492]
      -  [1179, 495, 3275, 653]
    lower:
      -  [6, 737, 413, 894]
      -  [2340, 1552, 3200, 1394]
      -  [3142, 1405, 3631, 1151]
      -  [423, 891, 1273, 1387]
      -  [1279, 1394, 2235, 1564]
      -  [3441, 1260, 3803, 1050]
      -  [3803, 1050, 4134, 712]

#
# Model config
#
model:
  backbone:
    type: dla34
    pretrained: True
    # pretrained_path: 'pretrained/centertrack/crowdhuman.pth'
    pretrained_path: 'pretrained/centertrack/coco_pose_tracking.pth'
    det_thres: 0.3

    train:

    test:

  tracker:
    type: centertrack
    conf_thres: 0.4
