game:
  name: tvbb2
  rink: dublin
  home: Blue Devils
  away: Cougars
  clip_box:
  - 50
  - 360
  - 3928
  - 1557
  boundaries:
    upper:
    - - 26
      - 1155
      - 393
      - 1128
    - - 393
      - 1128
      - 626
      - 1031
    - - 626
      - 1031
      - 1354
      - 849
    - - 1354
      - 849
      - 1796
      - 793
    - - 1796
      - 793
      - 2546
      - 804
    - - 2546
      - 804
      - 3218
      - 863
    - - 3218
      - 863
      - 3952
      - 959
    - - 3952
      - 959
      - 4377
      - 1036
    - - 4377
      - 1036
      - 4709
      - 1126
    - - 4709
      - 1126
      - 5165
      - 1258
    - - 5165
      - 1258
      - 5495
      - 1377
    - - 5495
      - 1377
      - 5745
      - 1395
    lower:
    - - 24
      - 1065
      - 363
      - 1094
    - - 363
      - 1094
      - 857
      - 1451
    - - 857
      - 1451
      - 1796
      - 1919
    - - 1796
      - 1921
      - 2993
      - 2162
    - - 2993
      - 2162
      - 3523
      - 2038
    - - 3523
      - 2038
      - 4381
      - 1842
    - - 4381
      - 1842
      - 5129
      - 1622
    - - 5129
      - 1622
      - 5347
      - 1496
    - - 5347
      - 1496
      - 5531
      - 1350
    - - 5531
      - 1350
      - 5729
      - 1112
rink:
  tracking:
    cam_ignore_largest: true
  scoreboard:
    perspective_polygon:
    - - 2900
      - 600
    - - 3224
      - 634
    - - 3214
      - 707
    - - 2895
      - 676
