game:
  name: "tvbb-1"
  rink: "vallco"
  home: "Cougars"
  away: "Tri-Valley Blue Devils 10BB"

  stitching:
    offsets: [15.39277049481131, 0]

  clip_box: [null, 200, null, null]
  boundaries:
    upper:
      - [291, 1135, 1187, 626]
      - [3067, 479, 4107, 927]
    lower:
      - [14, 1102, 306, 1105]
      - [294, 1134, 931, 1850]
      - [7, 1163, 318, 1162]
      - [2992, 1606, 3667, 1094]
      - [3668, 1094, 3866, 802]
      - [3866, 802, 4240, 824]
rink:
  camera:
    fixed_edge_scaling_factor: 1.25
    fixed_edge_rotation_angle: 40
