game:
  name: tvbb2
  rink: dublin
  home: Blue Devils
  away: Cougars
  boundaries:
    upper:
    - - 25
      - 1112
      - 393
      - 1132
    - - 393
      - 1132
      - 607
      - 1043
    - - 607
      - 1043
      - 1410
      - 842
    - - 1410
      - 842
      - 2034
      - 786
    - - 2034
      - 786
      - 3009
      - 842
    - - 3011
      - 842
      - 3817
      - 935
    - - 3817
      - 935
      - 4425
      - 1043
    - - 4425
      - 1043
      - 4918
      - 1188
    - - 4918
      - 1188
      - 5373
      - 1330
    - - 5373
      - 1330
      - 5762
      - 1432
    lower:
    - - 25
      - 1012
      - 389
      - 1123
    - - 389
      - 1123
      - 1348
      - 1701
    - - 1348
      - 1701
      - 2956
      - 2184
    - - 3307
      - 2175
      - 3586
      - 2029
    - - 3586
      - 2029
      - 4510
      - 1878
    - - 4510
      - 1878
      - 5271
      - 1550
    - - 5271
      - 1550
      - 5556
      - 1354
    - - 5556
      - 1354
      - 5757
      - 1345
rink:
  tracking:
    cam_ignore_largest: true
  scoreboard:
    perspective_polygon:
    - - 2900
      - 597
    - - 3226
      - 630
    - - 3216
      - 706
    - - 2897
      - 674
