game:
  name: "wolves"
  rink: "orlando_ice_den"
  home: "Queens Something"
  away: "Cougars"
  stitching:
    offsets: [-8.16054693605714, 0]
  clip_box: null
  boundaries:
   upper:
      - [521, 1462, 623, 1324]
      - [623, 1330, 1330, 824]
      - [1325, 823, 1670, 654]
      - [1670, 654, 2193, 499]
      - [2193, 499, 2904, 400]
      - [2904, 400, 3558, 396]
      - [3562, 389, 4157, 469]
      - [4157, 469, 4682, 627]
      - [4682, 627, 5356, 1036]
      - [5356, 1042, 5662, 1316]
   lower:
      - [1, 1369, 511, 1351]
      - [504, 1454, 1058, 2214]
      - [4983, 2218, 5707, 1219]
      - [5707, 1219, 6044, 1220]
