rink:
  scoreboard:
    perspective_polygon:
    - - 3516
      - 169
    - - 3700
      - 256
    - - 3682
      - 322
    - - 3500
      - 229
game:
  boundaries:
    upper:
    - - 0
      - 1318
      - 222
      - 1059
    - - 220
      - 1058
      - 696
      - 687
    - - 690
      - 684
      - 974
      - 513
    - - 974
      - 513
      - 1319
      - 359
    - - 1316
      - 359
      - 1904
      - 169
    - - 1904
      - 169
      - 2203
      - 121
    - - 2202
      - 122
      - 2727
      - 150
    - - 2722
      - 148
      - 3070
      - 211
    - - 3070
      - 211
      - 3447
      - 362
    - - 3447
      - 362
      - 3845
      - 609
    - - 3845
      - 609
      - 4090
      - 896
    - - 2457
      - 181
      - 2494
      - 182
    - - 2720
      - 195
      - 2743
      - 195
    - - 1548
      - 322
      - 1571
      - 324
    - - 1470
      - 348
      - 1508
      - 348
    - - 694
      - 733
      - 730
      - 730
    - - 870
      - 610
      - 902
      - 610
    - - 472
      - 948
      - 495
      - 948
    - - 1161
      - 457
      - 1190
      - 461
    - - 3812
      - 666
      - 3844
      - 662
    lower:
    - - 3
      - 1319
      - 230
      - 1818
    - - 3684
      - 1798
      - 4024
      - 770
  tracking:
    #
    # Some tracking config
    #
    cam_ignore_largest: true

  camera:
    #
    # Configuration for breakaways
    #
    breakaway_detection:
      # What ratio of the group speed should we try to
      # apply within a single frame's speed adjustment?
      group_velocity_speed_ratio: 0.2
      # During a breakaway, what scale do we adjust the
      # maximum camera speed to allow for faster-than-normal tracking?
      scale_speed_constraints: 1.5
      # The number of frame steps to not allow any camera-stop conditions to
      # trigger such as cluster(s) direction change or "sticky translation" rules.
      # This is because the clusters may not have changed enough at the
      # beginning of a breakaway and may simply stop the camera movement
      # due to the cluster tracking rules.
      nonstop_delay_count: 2
      # When over-shooting the breakaway players, what scale do we apply
      # to the current speed each frame in order to slow it down?
      overshoot_scale_speed_ratio: 0.6
